#!/usr/bin/env python3
"""meaningful_diff.py — exit 0 if any given path differs from HEAD in more
than its own generation timestamp, exit 1 if every path is either absent or
byte-identical to HEAD once timestamps are normalized away.

Every export this repo commits stamps itself with the moment it ran —
meta.generatedAt / generated_at / lastSynced, and the "GENERATED ... on"
banner comment — even when the underlying teams/matches/coverage facts are
identical to what is already committed. A raw `git diff --cached --quiet`
cannot tell "real data changed" from "only the clock moved", so a scheduled
run that found nothing new would still open a data-update PR every hour —
exactly the kind of empty, timestamp-only PR the automation must never
open. This normalizes away exactly those volatile timestamp fields
(nothing else) before comparing.

Usage: python3 pipeline/automation/meaningful_diff.py <path> [<path> ...]
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

_BANNER_TS = re.compile(
    rb"(GENERATED by [^\n]*? on )\d{4}-\d{2}-\d{2} \d{2}:\d{2}( UTC)")
_ISO_TS = re.compile(
    rb'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?\+00:00')


def _committed_bytes(path: str) -> bytes | None:
    r = subprocess.run(["git", "show", f"HEAD:{path}"], capture_output=True)
    return r.stdout if r.returncode == 0 else None


def normalize(data: bytes) -> bytes:
    """Blank out generation timestamps in TEXT content; binary content
    (e.g. the sqlite DB) is returned unchanged, since it has no reliably
    parseable timestamp field and an exact-bytes comparison is the safe
    default there."""
    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        return data
    data = data.replace(b"\r\n", b"\n")
    data = _BANNER_TS.sub(rb"\g<1><TS>\g<2>", data)
    data = _ISO_TS.sub(b"<TS>", data)
    return data


def has_meaningful_change(path: str) -> bool:
    p = Path(path)
    if not p.exists():
        return False
    working = p.read_bytes()
    old = _committed_bytes(path)
    if old is None:
        return True  # new file — definitely a real change
    return normalize(old) != normalize(working)


def main(argv: list[str]) -> int:
    if not argv:
        print("usage: meaningful_diff.py <path> [<path> ...]", file=sys.stderr)
        return 2
    changed = False
    for path in argv:
        if has_meaningful_change(path):
            print(f"CHANGED  {path}")
            changed = True
        else:
            print(f"unchanged (timestamp only, or absent)  {path}")
    return 0 if changed else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
