#!/usr/bin/env python3
"""
build_hero_art_index.py — the tiny index that lets every page draw hero
portraits without a fetch.

`assets/data/asset_manifest.json` is ~100 KB and describes every asset in
the repo. The product UI needs one bit per hero — "is there official
presentation art on disk for this id" — because the paths themselves are
conventional:

    assets/img/heroes/official/<id>/icon.webp      (64px)
    assets/img/heroes/official/<id>/portrait.webp  (256px)
    assets/img/heroes/official/<id>/artwork.webp   (960px)

So this writes a few-hundred-byte JS constant instead, which every page
loads synchronously. No page has to wait on a manifest fetch before it can
render a composition, which is what a review screen does every few seconds.

The evidence path is deliberately NOT in here. A broadcast crop proving
what a detector actually saw lives in the public export as `portraitUrl`
and is resolved separately — this file only answers "what does this hero
look like", never "what did we see".

Usage:
  python3 pipeline/build_hero_art_index.py            # write the index
  python3 pipeline/build_hero_art_index.py --check    # verify it is current
"""
from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import proc_text  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART_DIR = os.path.join(ROOT, "assets", "img", "heroes", "official")
OUT_PATH = os.path.join(ROOT, "assets", "data", "hero_art.v1.js")

HEADER = """\
/* =====================================================================
   OWCS Comp Tracker — hero_art.v1.js
   GENERATED by pipeline/build_hero_art_index.py — do not hand-edit.

   Which hero ids have official presentation art on disk. Paths are
   conventional (assets/img/heroes/official/<id>/{icon,portrait,artwork}
   .webp), so the ids are the whole index.
   ===================================================================== */
"""


def scan() -> list[str]:
    """Hero ids with a usable official portrait, sorted."""
    if not os.path.isdir(ART_DIR):
        return []
    found = []
    for name in sorted(os.listdir(ART_DIR)):
        folder = os.path.join(ART_DIR, name)
        if not os.path.isdir(folder):
            continue
        portrait = os.path.join(folder, "portrait.webp")
        if os.path.exists(portrait) or os.path.exists(
                os.path.join(folder, "portrait.png")):
            found.append(name)
    return found


def render(ids: list[str]) -> str:
    body = json.dumps(ids, indent=0).replace("\n", "")
    return f"{HEADER}window.OWCS_HERO_ART = {body};\n"


def main() -> int:
    # This prints '—' in its --check line, which test_assets.py captures and
    # re-prints. Without UTF-8 out, Windows encodes it in the ANSI code page,
    # the parent's UTF-8 decode turns it into U+FFFD, and the parent then dies
    # printing that. proc_text is explicit that every entry point here calls
    # this before it prints; this one had been missed.
    proc_text.enable_utf8_stdio()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed index is stale")
    args = ap.parse_args()

    ids = scan()
    text = render(ids)

    if args.check:
        try:
            with open(OUT_PATH, encoding="utf-8") as f:
                current = f.read()
        except OSError:
            print(f"MISSING {OUT_PATH} — run this script without --check")
            return 1
        if current != text:
            print(f"STALE {OUT_PATH} — run pipeline/build_hero_art_index.py")
            return 1
        print(f"OK — {len(ids)} hero(es) with official art")
        return 0

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(OUT_PATH, ROOT)} — {len(ids)} hero(es)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
