#!/usr/bin/env python3
"""
export_data.py — publish the SQLite database to the static website.

Reads data/owcs.sqlite and writes assets/js/data.js as window.OWCS_DATA.
Milestone 1 exports both completed comp data and partial FACEIT matchroom
metadata, so the frontend can show useful map order, bans, replay codes, and
empty states before computer vision has processed a match.

Usage:
  python3 pipeline/export_data.py            # writes assets/js/data.js
  python3 pipeline/export_data.py --stdout   # print JSON to stdout instead
"""
from __future__ import annotations
import argparse
import datetime as dt
import difflib
import itertools
import json
import os
import re
import sys
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db  # noqa: E402

OUT_PATH = os.path.join(db.REPO_ROOT, "assets", "js", "data.js")
SOURCES_PATH = os.path.join(db.REPO_ROOT, "data", "sources",
                            "video_sources.json")


def load_video_sources(path: str = SOURCES_PATH) -> list[dict]:
    """Metadata-only view of video_sources.json for the static site."""
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            entries = json.load(f).get("sources", []) or []
    except (ValueError, OSError):
        return []
    out = []
    for s in entries:
        sid = s.get("id") or s.get("match")
        if not sid:
            continue
        out.append({
            "id": sid,
            "title": s.get("title") or sid,
            "url": s.get("url") or s.get("vodUrl"),
            "platform": s.get("platform") or ("demo" if s.get("fixtureFrames") else "unknown"),
            "date": s.get("date"),
            "region": s.get("region"),
            "enabled": s.get("enabled", True),
            "layout": s.get("layout"),
            "mode": s.get("mode"),
            "notes": s.get("notes"),
        })
    return out

PORTRAIT_DIR = os.path.join(db.REPO_ROOT, "assets", "img", "heroes")


def hero_portraits() -> dict[str, str]:
    """{hero_id: site-relative url} for every hero with a REAL broadcast
    portrait (generated by pipeline/build_hero_portraits.py from harvested
    template crops). Heroes without one fall back to monogram tiles."""
    out: dict[str, str] = {}
    if os.path.isdir(PORTRAIT_DIR):
        for fn in sorted(os.listdir(PORTRAIT_DIR)):
            if fn.endswith(".png"):
                out[fn[:-4]] = f"assets/img/heroes/{fn}"
    return out


def attach_portraits(heroes: list[dict]) -> list[dict]:
    ports = hero_portraits()
    for h in heroes:
        if h["id"] in ports:
            h["portraitUrl"] = ports[h["id"]]
    return heroes


HEADER = """/* =====================================================================
   OWCS Comp Tracker — data.js
   GENERATED by pipeline/export_data.py on {ts} UTC — do not hand-edit.
   ===================================================================== */

window.OWCS_DATA = """


def rv(row: Any, key: str, default: Any = None) -> Any:
    """sqlite3.Row safe getter that also tolerates older DBs."""
    if row is None:
        return default
    try:
        return row[key]
    except Exception:
        return default


def snapshot_comp(con, snapshot_id: int) -> list[str]:
    return [r["hero_id"] for r in con.execute(
        "SELECT hero_id FROM snapshot_heroes WHERE snapshot_id=? ORDER BY slot",
        (snapshot_id,),
    ).fetchall()]


def comp_info_for_map(con, map_result_id: int, team_id: str) -> dict:
    """Union of heroes seen for this team on this map, ordered by the best
    snapshot's slots first. Opener is the earliest snapshot. Swap heroes are
    anything seen beyond the first five opener heroes."""
    snaps = con.execute(
        """SELECT id, overall_confidence, stream_offset_seconds,
                  COALESCE(source,'cv') AS source
           FROM comp_snapshots
           WHERE map_result_id=? AND team_id=?
           ORDER BY stream_offset_seconds ASC, id ASC""",
        (map_result_id, team_id),
    ).fetchall()
    # Manual corrections override every other source outright.
    manual = [s_ for s_ in snaps if s_["source"] == "manual"]
    if manual:
        snaps = manual
    if not snaps:
        return {"comp": [], "opener": [], "swaps": [], "confidence": None}

    opener = snapshot_comp(con, snaps[0]["id"])
    best = sorted(snaps, key=lambda s: (rv(s, "overall_confidence", 0) or 0), reverse=True)[0]
    comp: list[str] = []
    for hid in snapshot_comp(con, best["id"]):
        if hid not in comp:
            comp.append(hid)
    for s in snaps:
        for hid in snapshot_comp(con, s["id"]):
            if hid not in comp:
                comp.append(hid)
    confidence_values = [rv(s, "overall_confidence") for s in snaps if rv(s, "overall_confidence") is not None]
    confidence = round(sum(confidence_values) / len(confidence_values), 3) if confidence_values else None
    return {
        "comp": comp,
        "opener": opener,
        "swaps": [hid for hid in comp if hid not in opener[:5]],
        "confidence": confidence,
    }


def hero_bans_for_map(con, match_id: str, map_result_id: int | None = None) -> list[dict]:
    if map_result_id is None:
        rows = con.execute(
            """SELECT * FROM hero_bans WHERE match_id=?
               ORDER BY COALESCE(map_order, 999), COALESCE(ban_order, id), id""",
            (match_id,),
        ).fetchall()
    else:
        rows = con.execute(
            """SELECT * FROM hero_bans WHERE map_result_id=?
               ORDER BY COALESCE(ban_order, id), id""",
            (map_result_id,),
        ).fetchall()
    return [{
        "hero": r["hero_id"],
        "heroId": r["hero_id"],
        "role": rv(r, "role"),
        "teamId": rv(r, "team_id"),
        "mapOrder": rv(r, "map_order"),
        "order": rv(r, "ban_order"),
        "source": rv(r, "source", "unknown"),
        "confidence": rv(r, "confidence"),
        "notes": rv(r, "notes"),
    } for r in rows]


def pick_veto_for_match(con, match_id: str) -> list[dict]:
    rows = con.execute(
        """SELECT * FROM map_veto_events WHERE match_id=? ORDER BY order_index, id""",
        (match_id,),
    ).fetchall()
    return [{
        "order": r["order_index"],
        "teamId": rv(r, "team_id"),
        "map": rv(r, "map_id"),
        "action": rv(r, "action", "unknown"),
        "source": rv(r, "source", "unknown"),
        "notes": rv(r, "notes"),
    } for r in rows]


# Players seeded as demo fixtures (source='sample', handles like
# 'GEN-TAN1') are never real people. They exist so the offline test
# fixtures have something to join against — publishing them would put
# invented handles on a public roster, which is exactly the kind of guess
# this project refuses to make. Every roster read filters them out.
SAMPLE_PLAYER_SOURCE = "sample"


def rosters_for_match(con, match_id: str, team_a: str, team_b: str) -> dict:
    """FACEIT-sourced lineups: {'a': [players], 'b': [players]}.
    This feeds the internal control-room dataset (assets/js/data.js),
    which is allowed to carry the labeled demo fixtures; the PUBLIC
    export filters them (see SAMPLE_PLAYER_SOURCE)."""
    out = {"a": [], "b": []}
    rows = con.execute(
        """SELECT r.team_id, p.id, p.nickname, p.role, p.faceit_player_id
           FROM match_rosters r JOIN players p ON p.id = r.player_id
           WHERE r.match_id=? ORDER BY p.role, p.nickname""", (match_id,))
    for r in rows:
        side = "a" if r["team_id"] == team_a else "b" if r["team_id"] == team_b else None
        if side:
            out[side].append({"id": r["id"], "nickname": r["nickname"],
                              "role": rv(r, "role"),
                              "faceitPlayerId": rv(r, "faceit_player_id")})
    return out


def comp_timeline(con, map_result_id: int, team_id: str) -> list[dict]:
    """Tracker-generated: every snapshot for this team on this map, in order."""
    rows = con.execute(
        """SELECT * FROM comp_snapshots WHERE map_result_id=? AND team_id=?
           ORDER BY stream_offset_seconds""", (map_result_id, team_id)).fetchall()
    manual = [r for r in rows if rv(r, "source", "cv") == "manual"]
    if manual:
        rows = manual
    out = []
    for s_ in rows:
        heroes = [r["hero_id"] for r in con.execute(
            "SELECT hero_id FROM snapshot_heroes WHERE snapshot_id=? ORDER BY slot",
            (s_["id"],))]
        out.append({"offsetSeconds": s_["stream_offset_seconds"],
                    "heroes": heroes,
                    "confidence": rv(s_, "overall_confidence"),
                    "source": rv(s_, "source", "cv")})
    return out


def winner_side(match_row, winner_team: str | None) -> str | None:
    if winner_team == match_row["team_a"]:
        return "a"
    if winner_team == match_row["team_b"]:
        return "b"
    return None


def load_auto_runs(path: str | None = None) -> list[dict]:
    """Recent run_owcs_auto.py run records for the static site."""
    path = path or os.path.join(db.REPO_ROOT, "data", "auto_runs.json")
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f).get("runs", []) or []
    except (ValueError, OSError):
        return []


def load_ingest_runs(con) -> list[dict]:
    """Full-map ingestion runs (pipeline/ingest_map.py) for the Vision Lab
    — calibration health, team identity, CV ban detections, round/swap
    counts, all linked to that run's evidence report. This is the newer,
    richer sibling of load_auto_runs (which only covers the older capture/
    detect batch path) and is what runs.html leads with."""
    try:
        rows = con.execute(
            "SELECT * FROM ingest_runs ORDER BY created_at DESC").fetchall()
    except Exception:      # table missing on a very old DB -> empty, not fatal
        return []
    out = []
    for r in rows:
        ingest_id = r["id"]
        match = con.execute("SELECT * FROM matches WHERE id=?",
                            (r["match_id"],)).fetchone()
        mr = con.execute(
            "SELECT * FROM map_results WHERE match_id=? AND map_order=?",
            (r["match_id"], r["map_order"])).fetchone()
        map_result_id = mr["id"] if mr else None
        n_rounds = (con.execute(
            "SELECT COUNT(*) FROM map_rounds WHERE map_result_id=?",
            (map_result_id,)).fetchone()[0] if map_result_id else 0)
        n_stints = con.execute(
            "SELECT COUNT(*) FROM hero_stints WHERE ingest_id=?",
            (ingest_id,)).fetchone()[0]
        n_swaps_confirmed = con.execute(
            "SELECT COUNT(*) FROM hero_swaps WHERE ingest_id=? "
            "AND status='confirmed'", (ingest_id,)).fetchone()[0]
        n_swaps_uncertain = con.execute(
            "SELECT COUNT(*) FROM hero_swaps WHERE ingest_id=? "
            "AND status='uncertain'", (ingest_id,)).fetchone()[0]
        n_bans = con.execute(
            "SELECT COUNT(*) FROM hero_bans WHERE ingest_id=?",
            (ingest_id,)).fetchone()[0]
        n_ban_candidates = con.execute(
            "SELECT COUNT(*) FROM ingest_findings WHERE ingest_id=? "
            "AND kind='ban_candidate'", (ingest_id,)).fetchone()[0]
        team_findings = [{
            "side": rv(tf, "field"), "team": rv(tf, "value"),
            "confidence": rv(tf, "confidence"), "status": rv(tf, "status"),
            "notes": rv(tf, "notes"),
        } for tf in con.execute(
            "SELECT * FROM ingest_findings WHERE ingest_id=? "
            "AND kind='team_identity' ORDER BY field", (ingest_id,))]
        try:
            calib_health = (json.loads(r["calibration_health"])
                            if rv(r, "calibration_health") else None)
        except (ValueError, TypeError):
            calib_health = None
        out.append({
            "id": ingest_id,
            "sourceId": rv(r, "source_id"),
            "matchId": r["match_id"],
            "matchTitle": (f"{match['team_a']} vs {match['team_b']}"
                          if match else r["match_id"]),
            "mapOrder": r["map_order"],
            "mapId": rv(mr, "map_id") if mr else None,
            "startOffset": rv(r, "start_offset"),
            "endOffset": rv(r, "end_offset"),
            "detectorVersion": r["detector_version"],
            "calibrationVersion": rv(r, "calibration_version"),
            "status": r["status"],
            "calibrationStatus": rv(r, "calibration_status", "ok"),
            "calibrationHealth": calib_health,
            "reportPath": rv(r, "report_path"),
            "createdAt": rv(r, "created_at"),
            "rounds": n_rounds,
            "stints": n_stints,
            "swapsConfirmed": n_swaps_confirmed,
            "swapsUncertain": n_swaps_uncertain,
            "bansConfirmed": n_bans,
            "banCandidates": n_ban_candidates,
            "teamFindings": team_findings,
        })
    return out


def build_payload(con) -> dict:
    heroes = attach_portraits([dict(r) for r in con.execute(
        "SELECT id, name, role FROM heroes ORDER BY role, name")])
    maps = [dict(r) for r in con.execute(
        "SELECT id, name, mode FROM game_maps ORDER BY name")]
    teams = [{
        "id": r["id"],
        "name": r["name"],
        "region": r["region"],
        "code": r["code"],
        "faceitTeamId": rv(r, "faceit_team_id"),
        "logoUrl": rv(r, "logo_url"),
        "prepNotes": rv(r, "prep_notes"),
    } for r in con.execute(
        "SELECT * FROM teams ORDER BY name")]

    prep_notes = [{
        "id": r["id"],
        "teamId": r["team_id"],
        "opponentTeamId": rv(r, "opponent_team_id"),
        "map": rv(r, "map_id"),
        "noteType": rv(r, "note_type", "general"),
        "note": r["note"],
        "source": rv(r, "source", "manual"),
        "updatedAt": rv(r, "updated_at"),
    } for r in con.execute(
        "SELECT * FROM team_prep_notes ORDER BY team_id, note_type, id")]

    matches_out = []
    for m in con.execute(
        """SELECT * FROM matches
           WHERE status IN ('upcoming','live','final','unknown')
           ORDER BY date, id"""
    ).fetchall():
        maps_out = []
        replay_codes: list[str] = []
        for mr in con.execute(
            "SELECT * FROM map_results WHERE match_id=? ORDER BY map_order",
            (m["id"],),
        ).fetchall():
            info_a = comp_info_for_map(con, mr["id"], m["team_a"])
            info_b = comp_info_for_map(con, mr["id"], m["team_b"])
            bans = hero_bans_for_map(con, m["id"], mr["id"])
            replay_code = rv(mr, "replay_code")
            if replay_code:
                replay_codes.append(replay_code)
            side = winner_side(m, rv(mr, "winner_team"))
            confidence_values = [v for v in [info_a["confidence"], info_b["confidence"], rv(mr, "confidence")] if v is not None]
            confidence = round(sum(confidence_values) / len(confidence_values), 3) if confidence_values else None
            tl_a = comp_timeline(con, mr["id"], m["team_a"])
            tl_b = comp_timeline(con, mr["id"], m["team_b"])
            detected = bool(info_a["comp"] or info_b["comp"])
            maps_out.append({
                "id": mr["id"],
                "map": mr["map_id"],
                "winner": side,                      # derived convenience
                # -------- FACEIT-sourced (matchroom facts) ----------------
                "faceit": {
                    "mapOrder": mr["map_order"],
                    "mapScores": {"a": rv(mr, "score_a"), "b": rv(mr, "score_b")},
                    "winnerTeam": rv(mr, "winner_team"),
                    "pickedByTeam": rv(mr, "picked_by_team"),
                    "vetoAction": rv(mr, "veto_action"),
                    "pickVeto": rv(mr, "pick_veto"),
                    "heroBans": bans,
                    "replayCode": replay_code,
                    "replayCodes": [replay_code] if replay_code else [],
                    "replayExpiresNote": rv(mr, "replay_expires_note"),
                    "vodUrl": rv(mr, "vod_url"),
                    "vodStartSeconds": rv(mr, "vod_start_seconds"),
                    "source": rv(mr, "source", "unknown"),
                    # provenance of the fact fields (replay/bans): 'manual_facts'
                    # if any manual fact bans exist or the map is manual-sourced,
                    # else the map's own source ('faceit' / 'sample').
                    "factSource": ("manual_facts"
                                   if any(b.get("source") == "manual_facts" for b in bans)
                                   else rv(mr, "source", "unknown")),
                },
                # -------- Tracker-generated (replay/VOD/CV/manual) --------
                "tracker": {
                    "detected": detected,
                    "openerCompA": info_a["opener"],
                    "openerCompB": info_b["opener"],
                    "playedHeroesA": info_a["comp"],
                    "playedHeroesB": info_b["comp"],
                    "swapsA": info_a["swaps"],
                    "swapsB": info_b["swaps"],
                    "compTimeline": {"a": tl_a, "b": tl_b},
                    "confidence": confidence if detected else None,
                    "source": ("manual" if any(x["source"] == "manual" for x in (tl_a + tl_b))
                               else (tl_a or tl_b)[0]["source"]) if detected and (tl_a or tl_b) else None,
                    # per-team provenance so each side's badge is accurate
                    "sourceA": tl_a[0]["source"] if tl_a else None,
                    "sourceB": tl_b[0]["source"] if tl_b else None,
                    "confidenceA": info_a["confidence"] if info_a["comp"] else None,
                    "confidenceB": info_b["confidence"] if info_b["comp"] else None,
                    "detectedA": bool(info_a["comp"]),
                    "detectedB": bool(info_b["comp"]),
                },
                "notes": rv(mr, "notes"),
            })

        match_bans = hero_bans_for_map(con, m["id"])
        match_pick_veto = pick_veto_for_match(con, m["id"])
        matches_out.append({
            "id": m["id"],
            "date": m["date"],
            "status": m["status"],
            "region": m["region"],
            "stage": rv(m, "stage") or "",
            "eventName": rv(m, "event_name"),
            "season": rv(m, "season"),
            "division": rv(m, "division"),
            "round": rv(m, "round"),
            "groupName": rv(m, "group_name"),
            "scheduledAt": rv(m, "scheduled_at"),
            "startedAt": rv(m, "started_at"),
            "finishedAt": rv(m, "finished_at"),
            "teamA": m["team_a"],
            "teamB": m["team_b"],
            "teams": [m["team_a"], m["team_b"]],
            "scoreA": rv(m, "score_a", 0),
            "scoreB": rv(m, "score_b", 0),
            "score": {"a": rv(m, "score_a", 0), "b": rv(m, "score_b", 0)},
            "winnerTeam": rv(m, "winner_team"),
            # -------- FACEIT-sourced (matchroom facts) --------------------
            "faceit": {
                "matchId": rv(m, "faceit_match_id"),
                "roomUrl": rv(m, "faceit_room_url"),
                "rosters": rosters_for_match(con, m["id"], m["team_a"], m["team_b"]),
                "pickVeto": match_pick_veto,
                "heroBans": match_bans,
                "replayCodes": replay_codes,
            },
            "sourceUrl": rv(m, "source_url"),
            "vodUrl": rv(m, "vod_url"),
            "rawSource": rv(m, "raw_source"),
            "prepNotes": rv(m, "prep_notes"),
            "updatedAt": rv(m, "updated_at"),
            "maps": maps_out,
        })

    return {
        "generatedAt": dt.datetime.now(dt.timezone.utc).isoformat(),
        "heroes": heroes,
        "maps": maps,
        "teams": teams,
        "teamPrepNotes": prep_notes,
        "matches": matches_out,
        "videoSources": load_video_sources(),
        "autoRuns": load_auto_runs(),
        "ingestRuns": load_ingest_runs(con),
    }


# ===================================================================
# Production public export (public.v1) — window.OWCS_PUBLIC
# ===================================================================
PUBLIC_OUT_PATH = os.path.join(db.REPO_ROOT, "assets", "data",
                               "public_data.v1.js")
PUBLIC_HEADER = """/* =====================================================================
   OWCS Comp Tracker — public_data.v1.js  (PRODUCTION public dataset)
   GENERATED by pipeline/export_data.py --public on {ts} UTC.
   Do not hand-edit. The demo fixture file is never touched by this
   exporter (guarded by pipeline/test_public_site.py).
   ===================================================================== */

window.OWCS_PUBLIC = """

REGIONS = [
    {"id": "all", "name": "All regions", "short": "ALL"},
    {"id": "na", "name": "North America", "short": "NA"},
    {"id": "emea", "name": "EMEA", "short": "EMEA"},
    {"id": "asia", "name": "Asia", "short": "ASIA"},
    {"id": "china", "name": "China", "short": "CN"},
    {"id": "pacific", "name": "Pacific", "short": "PAC"},
    # The official calendar names these regions too. Without them a region
    # badge falls back to the raw id ("korea"), which is how the calendar's
    # event bands were rendering before.
    {"id": "korea", "name": "Korea", "short": "KR"},
    {"id": "japan", "name": "Japan", "short": "JP"},
    {"id": "global", "name": "Global", "short": "GLOBAL"},
]


TEAM_ASSET_SOURCES_PATH = os.path.join(db.REPO_ROOT, "assets", "data", "team_asset_sources.json")


def _json_list(raw: str | None) -> list[str]:
    if not raw:
        return []
    try:
        val = json.loads(raw)
        return val if isinstance(val, list) else []
    except (TypeError, ValueError):
        return []


def _team_asset_sources(path: str = TEAM_ASSET_SOURCES_PATH) -> dict:
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f).get("teams", {})


def _has_logo_candidate(team_id: str, sources: dict) -> bool:
    entry = sources.get(team_id, {})
    return bool(entry.get("candidateSources") or entry.get("assetCandidates"))


def _current_roster(con, team_id: str) -> list[dict]:
    """Players from this team's most recent match that has a REAL lineup —
    the closest thing to a 'current roster' the content DB can state as
    fact. Demo-fixture players (source='sample') are skipped entirely, so
    a team whose only lineups are fixtures exports an empty roster rather
    than invented handles. Empty (never guessed) is always allowed."""
    rows = con.execute(
        """SELECT r.match_id, p.id, p.nickname, p.role, p.country
             FROM match_rosters r
             JOIN players p ON p.id = r.player_id
             JOIN matches  m ON m.id = r.match_id
            WHERE r.team_id = ? AND COALESCE(p.source,'') <> ?
            ORDER BY COALESCE(m.scheduled_at, m.finished_at, m.date) DESC,
                     r.match_id DESC""",
        (team_id, SAMPLE_PLAYER_SOURCE)).fetchall()
    if not rows:
        return []
    newest = rows[0]["match_id"]          # the query is already ordered
    return [{"id": p["id"], "handle": p["nickname"], "role": rv(p, "role"),
             "country": rv(p, "country")}
            for p in rows if p["match_id"] == newest]


def _has_table(con, name: str) -> bool:
    return con.execute(
        "SELECT 1 FROM sqlite_master WHERE type IN ('table','view') AND name=?",
        (name,)).fetchone() is not None


def _region_id(raw: str | None) -> str:
    r = (raw or "").strip().lower()
    return r if r in {x["id"] for x in REGIONS} else "all"


def _tournament_id(m: Any) -> str:
    """Stable slug from the match's real event/season/stage — never a
    single hardcoded id, so two matches from different events never get
    silently lumped into (or overwrite) the same tournament."""
    import re
    parts = [rv(m, "event_name") or "owcs", rv(m, "season") or "",
             rv(m, "stage") or ""]
    slug = re.sub(r"[^a-z0-9]+", "-", "-".join(parts).lower()).strip("-")
    return slug or "owcs-2026"


def _discovery_window_days() -> tuple[int, int]:
    """(lookback, horizon) from config/automation.yml, defaulting safely if the
    automation package/config is unavailable."""
    try:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from automation import config as _acfg  # noqa: WPS433
        c = _acfg.load_config()
        return c.lookback_days, c.schedule_horizon_days
    except Exception:
        return 14, 30


def _fixture_kind(m: Any) -> str:
    """'production' or 'synthetic' for a matches row (see
    automation/match_repair.py — evidence is the row's own source_ref/
    faceit_match_id, never a guess). Falls back to 'production' (never
    hides a match) if the automation package isn't importable yet."""
    try:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from automation import match_repair as _mrepair  # noqa: WPS433
        return _mrepair.classify_fixture_kind(m)
    except Exception:
        return "production"


def _discovered_window_matches(con) -> list[Any]:
    """Content-DB matches the exporter should surface outside the CV-ingest
    path, ordered for a stable export.

    Two evidence-based eligibility routes (Phase D2.1):
      * FACEIT/calendar-discovered (competition_id or lifecycle_status set)
        — kept only inside the rolling discovery window, as before.
      * Already-concluded (status='final') — a match that already happened
        is a historical record, not a discovery-recency question, so it is
        NEVER excluded by the rolling window; the only thing that can hide
        it is being a synthetic sample fixture (pipeline/sample_data.json,
        classified via _fixture_kind). This closes the match-export gap for
        legacy real matches (e.g. m-cr-zeta-krgf) that predate the Phase B
        automation columns and would otherwise silently vanish from the
        calendar, match directory, tournament pages, team history, search
        and stats despite having real evidence (VODs, map results) on file.
        A bare *unconfirmed upcoming* stub (status != 'final', no
        competition_id/lifecycle_status) is still never fabricated onto the
        calendar — only a concluded match gets this bypass.

    Returns [] on a pre-migration DB that has no discovery columns yet, so
    the public export never crashes on an older DB."""
    cols = {r["name"] for r in con.execute("PRAGMA table_info(matches)")}
    if not {"competition_id", "lifecycle_status"} <= cols:
        return []
    lookback, horizon = _discovery_window_days()
    now = dt.datetime.now(dt.timezone.utc)
    past = (now - dt.timedelta(days=lookback)).date().isoformat()
    future = (now + dt.timedelta(days=horizon)).date().isoformat()
    rows = con.execute(
        """SELECT * FROM matches
           WHERE competition_id IS NOT NULL OR lifecycle_status IS NOT NULL
              OR status='final'
           ORDER BY COALESCE(scheduled_at, finished_at, date), id"""
    ).fetchall()
    out = []
    for m in rows:
        if _fixture_kind(m) == "synthetic":
            continue
        if (m["status"] or "").lower() == "final":
            out.append(m)
            continue
        when = (rv(m, "scheduled_at") or rv(m, "finished_at") or m["date"] or "")[:10]
        if not when:
            out.append(m)
            continue
        if when < past or when > future:
            continue
        out.append(m)
    return out


def _public_match_status(m: Any) -> str:
    """Map the FACEIT lifecycle/content status onto the public vocab
    (upcoming/live/completed/forfeit/cancelled)."""
    lifecycle = (rv(m, "lifecycle_status") or "").lower()
    if lifecycle in ("cancelled", "aborted"):
        return "cancelled"
    if lifecycle == "forfeit":
        return "forfeit"
    if lifecycle == "live":
        return "live"
    if lifecycle == "finished":
        return "completed"
    status = (m["status"] or "").lower()
    return {"upcoming": "upcoming", "live": "live",
            "final": "completed"}.get(status, "upcoming")


def _public_capture_status(m: Any, has_vod: bool, has_maps: bool) -> str | None:
    """Coarse capture state for the public chip. None for cancelled (no
    capture is expected). Vocab matches assets/js/public/core.js CAPTURE_LABELS."""
    lifecycle = (rv(m, "lifecycle_status") or "").lower()
    if lifecycle in ("cancelled", "aborted"):
        return None
    if has_maps:
        return "needs-review"
    if has_vod:
        return "queued"
    return "needs-source"


#: Public match statuses that mean "this match will not be played again".
_MATCH_STATUS_SETTLED = frozenset({"completed", "forfeit", "cancelled"})


def _reconcile_stub_tournament_status(tournaments_by_id: dict,
                                      stub_tids: set,
                                      matches_out: list) -> None:
    """Derive a stub tournament's status from the matches it actually holds.

    A tournament invented from a discovered match has no lifecycle of its own,
    so it is stubbed as "upcoming". Left alone that guess goes stale the moment
    its matches finish, and the site then asserts two contradictory things at
    once — an "UPCOMING" event chip above a full set of final scores. The
    public data's whole claim is that it never states something it cannot
    support, so the guess is reconciled here instead of being rendered.

    Only auto-stubbed tournaments are touched: a curated event carries an
    authoritative status that must win over anything inferred from matches.

    live     - any match in progress
    completed- at least one match played and none still to come
    upcoming - anything else (including an all-cancelled event, which has
               nothing to show and must not claim to be finished)
    """
    if not stub_tids:
        return
    by_tid: dict = {}
    for mo in matches_out:
        by_tid.setdefault(mo.get("tournamentId"), []).append(
            (mo.get("status") or "").lower())

    for tid in stub_tids:
        statuses = by_tid.get(tid) or []
        if not statuses:
            continue
        if "live" in statuses:
            derived = "live"
        elif ("completed" in statuses
              and all(s in _MATCH_STATUS_SETTLED for s in statuses)):
            derived = "completed"
        else:
            derived = "upcoming"
        t = tournaments_by_id[tid]
        t["status"] = derived
        # The lone auto-stubbed stage stands for the whole event, so it must
        # not contradict the parent it was created alongside.
        for stage in t.get("stages") or []:
            stage["status"] = derived


def _fmt_clock(seconds: int | None) -> str | None:
    if seconds is None:
        return None
    s = int(seconds)
    return f"{s // 3600}:{(s % 3600) // 60:02d}:{s % 60:02d}"


def _stints_for_map(con, map_result_id: int):
    return con.execute(
        """SELECT * FROM hero_stints WHERE map_result_id=?
           ORDER BY team_id, slot, start_offset""",
        (map_result_id,)).fetchall()


def _snapshot_times(con, map_result_id: int, team_id: str,
                    rounds: list) -> list[int]:
    """Round starts + every moment this team's comp changed."""
    times = {int(r["start_offset"]) for r in rounds
             if rv(r, "start_offset") is not None}
    for s in con.execute(
            """SELECT status, offset_seconds FROM hero_swaps
               WHERE map_result_id=? AND team_id=? AND status='confirmed'""",
            (map_result_id, team_id)):
        times.add(int(s["offset_seconds"]))
    return sorted(times)


def _comp_at(stints, team_id: str, t: int) -> tuple[list, list]:
    """(heroes[5], contributing stint rows) for one team at time t."""
    heroes, rows = [], []
    for slot in range(1, 6):
        cand = [s for s in stints
                if s["team_id"] == team_id and s["slot"] == slot
                and s["start_offset"] <= t + 15
                and (rv(s, "end_offset") or 10**9) >= t]
        if cand:
            # the stint that started most recently before t wins
            best = sorted(cand, key=lambda s: -s["start_offset"])[0]
            heroes.append(best["hero_id"])
            rows.append(best)
    return heroes, rows


def _nearest_frame(frames_dir_rel: str, t: int) -> str | None:
    """Closest copied evidence frame (reports/.../frames/frame_<t>.jpg)."""
    d = os.path.join(db.REPO_ROOT, frames_dir_rel)
    if not os.path.isdir(d):
        return None
    best, best_d = None, None
    for fn in os.listdir(d):
        if not fn.startswith("frame_"):
            continue
        try:
            ft = int(fn.split("_")[1].split(".")[0])
        except ValueError:
            continue
        dist = abs(ft - t)
        if best_d is None or dist < best_d:
            best_d, best = dist, fn
    if best is not None and best_d is not None and best_d <= 60:
        return f"{frames_dir_rel}/{best}"
    return None


def _layout_for_source(source_id: str | None) -> str | None:
    """Resolve a source id to its calibration layout file. Registered
    sources declare it in video_sources.json; ingest-only sources (e.g.
    owcs-jksix-qwc) follow the slug convention layouts/<id_>.json."""
    if not source_id:
        return None
    for s in load_video_sources():
        if s["id"] == source_id and s.get("layout"):
            p = os.path.join(db.REPO_ROOT, s["layout"])
            return p if os.path.exists(p) else None
    slug = source_id.replace("-", "_")
    p = os.path.join(db.REPO_ROOT, "layouts", f"{slug}.json")
    return p if os.path.exists(p) else None


def calibration_summary(source_id: str | None, roster: int) -> dict | None:
    """Compact, honest autocalibration provenance for a broadcast: the
    confidence the auto-calibrator earned, whether the gameplay-filter
    probe is present, and how much of the roster is templated. Powers the
    'why you can trust this footage' story on team/match pages. Returns
    None when the layout can't be found (never invents numbers)."""
    import re as _re
    path = _layout_for_source(source_id)
    if not path:
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            layout = json.load(f)
    except (OSError, ValueError):
        return None
    cal = layout.get("calibration") or {}
    tdir = layout.get("templates_dir")
    heroes = 0
    if tdir and os.path.isdir(os.path.join(db.REPO_ROOT, tdir)):
        name_re = _re.compile(r"^([a-z0-9_-]+?)(?:\.(?:v\d+|[a-z]))?\.png$")
        seen = set()
        for fn in os.listdir(os.path.join(db.REPO_ROOT, tdir)):
            m = name_re.match(fn)
            if m:
                seen.add(m.group(1))
        heroes = len(seen)
    return {
        "sourceId": source_id,
        "confidence": cal.get("confidence"),
        "hudProbe": bool(layout.get("hud_probe")),
        "rejectMarkers": len(layout.get("reject") or []),
        "templateHeroes": heroes,
        "roster": roster,
        "frameSize": [layout.get("frame_width"), layout.get("frame_height")],
    }


# =====================================================================
# Derived public aggregates (Phase 7)
# ---------------------------------------------------------------------
# The public pages have always computed pick/win rates in the browser from
# `compSnapshots` (see assets/js/public/stats.js). These functions compute
# the SAME aggregates server-side, from the SAME approved inputs and the same
# credibility rules, so the export can carry them for consumers that don't
# run the page's JS — and so the numbers can be validated in a test rather
# than only eyeballed in a browser.
#
# THE RULE, identical to stats.js's: only comp snapshots whose reviewStatus
# is 'reviewed' or 'auto-high' and whose source is 'cv' or 'manual' count. A
# manual snapshot overrides the cv one it corrects. Anything else — including
# every unreviewed detection — contributes to nothing.
# =====================================================================
APPROVED_REVIEW_STATES = ("reviewed", "auto-high")


def approved_snapshots(snapshots: list[dict]) -> list[dict]:
    """The publishable subset — the one gate every aggregate below shares."""
    overridden = {c["overridesId"] for c in snapshots if c.get("overridesId")}
    return [c for c in snapshots
            if c.get("reviewStatus") in APPROVED_REVIEW_STATES
            and c.get("source") in ("cv", "manual")
            and c["id"] not in overridden]


def _map_index(matches: list[dict]) -> dict[str, dict]:
    """{public map id -> {match, mapRow}} for result/mode lookups."""
    out = {}
    for m in matches:
        for g in m.get("maps") or []:
            out[g["id"]] = {"match": m, "map": g}
    return out


def _appearances(snapshots: list[dict], matches: list[dict]) -> list[dict]:
    """One appearance per (map, team): the five heroes that team fielded, and
    whether they won that map. This is the unit every rate below divides by —
    matching stats.js exactly, so a page and the export can never disagree
    about a denominator."""
    idx = _map_index(matches)
    by_key: dict[str, dict] = {}
    for c in approved_snapshots(snapshots):
        key = f"{c['mapId']}|{c['teamId']}"
        entry = by_key.get(key)
        if entry is None:
            info = idx.get(c["mapId"]) or {}
            map_row = info.get("map") or {}
            winner = map_row.get("winner")
            entry = {
                "mapId": c["mapId"], "matchId": c["matchId"],
                "teamId": c["teamId"], "map": map_row.get("map"),
                "mode": map_row.get("mode"),
                # A live/unscored map counts PICKS but never a win or a loss.
                "result": (None if not winner else
                           ("win" if winner == c["teamId"] else "loss")),
                "heroes": {}, "snapshotIds": [],
            }
            by_key[key] = entry
        entry["snapshotIds"].append(c["id"])
        for h in c.get("heroes") or []:
            entry["heroes"].setdefault(h, []).append(c["id"])
    return list(by_key.values())


def comp_key(heroes) -> str:
    """A composition's stable identity: its five hero ids, sorted. Sorting is
    what makes the same five heroes one comp regardless of slot order."""
    return "+".join(sorted(set(heroes)))


def build_comp_stats(snapshots: list[dict], matches: list[dict]) -> tuple[list, list]:
    """(compFrequency, compWinRate).

    A comp is counted once per (map, team) appearance, not once per snapshot —
    otherwise a map sampled ten times would look ten times as popular.
    `winRate` is None (not 0) when no appearance of that comp is on a decided
    map: no evidence is not a 0% win rate.
    """
    apps = _appearances(snapshots, matches)
    total = len(apps)
    buckets: dict[str, dict] = {}
    for a in apps:
        heroes = sorted(a["heroes"])
        if len(heroes) != 5:
            continue          # a partial read is never a composition
        key = comp_key(heroes)
        b = buckets.setdefault(key, {
            "id": key, "heroes": heroes, "appearances": 0, "wins": 0,
            "losses": 0, "teamIds": [], "evidence": []})
        b["appearances"] += 1
        if a["result"] == "win":
            b["wins"] += 1
        elif a["result"] == "loss":
            b["losses"] += 1
        if a["teamId"] not in b["teamIds"]:
            b["teamIds"].append(a["teamId"])
        b["evidence"].append({"matchId": a["matchId"], "mapId": a["mapId"],
                              "teamId": a["teamId"], "result": a["result"],
                              "snapshotIds": a["snapshotIds"]})
    freq, winrate = [], []
    for b in sorted(buckets.values(),
                    key=lambda x: (-x["appearances"], x["id"])):
        decided = b["wins"] + b["losses"]
        freq.append({"id": b["id"], "heroes": b["heroes"],
                     "appearances": b["appearances"],
                     "frequency": round(b["appearances"] / total, 5) if total else 0,
                     "teamIds": sorted(b["teamIds"]),
                     "evidence": b["evidence"]})
        winrate.append({"id": b["id"], "heroes": b["heroes"],
                        "wins": b["wins"], "losses": b["losses"],
                        "decidedMaps": decided,
                        "winRate": (round(b["wins"] / decided, 5)
                                    if decided else None),
                        "note": (None if decided else
                                 "no decided map for this comp yet — win rate "
                                 "is unknown, not zero")})
    return freq, winrate


def build_hero_rates(snapshots: list[dict], swaps: list[dict],
                     matches: list[dict]) -> list[dict]:
    """heroPickRates: pick rate, win rate and swap rate per hero.

    `swapRate` counts CONFIRMED swaps only — a rejected swap candidate is
    evidence the detector threw something out, never a hero behavior.
    """
    apps = _appearances(snapshots, matches)
    total = len(apps)
    rows: dict[str, dict] = {}
    for a in apps:
        for hero, snap_ids in a["heroes"].items():
            r = rows.setdefault(hero, {"hero": hero, "picks": 0, "wins": 0,
                                       "losses": 0, "swappedFrom": 0,
                                       "swappedTo": 0, "evidence": []})
            r["picks"] += 1
            if a["result"] == "win":
                r["wins"] += 1
            elif a["result"] == "loss":
                r["losses"] += 1
            r["evidence"].append({"matchId": a["matchId"], "mapId": a["mapId"],
                                  "teamId": a["teamId"], "result": a["result"],
                                  "snapshotIds": snap_ids})
    confirmed = [s for s in swaps if s.get("status") == "confirmed"]
    for s in confirmed:
        if s.get("fromHero"):
            rows.setdefault(s["fromHero"], {
                "hero": s["fromHero"], "picks": 0, "wins": 0, "losses": 0,
                "swappedFrom": 0, "swappedTo": 0, "evidence": []})
            rows[s["fromHero"]]["swappedFrom"] += 1
        if s.get("toHero"):
            rows.setdefault(s["toHero"], {
                "hero": s["toHero"], "picks": 0, "wins": 0, "losses": 0,
                "swappedFrom": 0, "swappedTo": 0, "evidence": []})
            rows[s["toHero"]]["swappedTo"] += 1
    out = []
    for r in rows.values():
        decided = r["wins"] + r["losses"]
        out.append({
            "hero": r["hero"], "picks": r["picks"],
            "pickRate": round(r["picks"] / total, 5) if total else 0,
            "wins": r["wins"], "losses": r["losses"],
            "winRate": round(r["wins"] / decided, 5) if decided else None,
            "swappedFrom": r["swappedFrom"], "swappedTo": r["swappedTo"],
            "swapRate": (round((r["swappedFrom"] + r["swappedTo"]) / r["picks"], 5)
                         if r["picks"] else None),
            "evidence": r["evidence"],
        })
    out.sort(key=lambda r: (-r["picks"], r["hero"]))
    return out


def build_team_hero_pools(snapshots: list[dict], matches: list[dict]) -> list[dict]:
    """teamHeroPools: which heroes each team has actually been seen on, with
    how often and on which maps. Only approved snapshots contribute, so a
    pool is a record of verified play rather than a guess at a preference."""
    apps = _appearances(snapshots, matches)
    teams: dict[str, dict] = {}
    for a in apps:
        t = teams.setdefault(a["teamId"], {"teamId": a["teamId"],
                                           "appearances": 0, "heroes": {}})
        t["appearances"] += 1
        for hero, snap_ids in a["heroes"].items():
            h = t["heroes"].setdefault(hero, {"hero": hero, "picks": 0,
                                              "wins": 0, "losses": 0,
                                              "maps": [], "snapshotIds": []})
            h["picks"] += 1
            if a["result"] == "win":
                h["wins"] += 1
            elif a["result"] == "loss":
                h["losses"] += 1
            if a["map"] and a["map"] not in h["maps"]:
                h["maps"].append(a["map"])
            h["snapshotIds"].extend(snap_ids)
    out = []
    for t in teams.values():
        heroes = []
        for h in t["heroes"].values():
            decided = h["wins"] + h["losses"]
            heroes.append(dict(h, maps=sorted(h["maps"]),
                               pickRate=(round(h["picks"] / t["appearances"], 5)
                                         if t["appearances"] else 0),
                               winRate=(round(h["wins"] / decided, 5)
                                        if decided else None)))
        heroes.sort(key=lambda h: (-h["picks"], h["hero"]))
        out.append({"teamId": t["teamId"], "appearances": t["appearances"],
                    "poolSize": len(heroes), "heroes": heroes})
    out.sort(key=lambda t: t["teamId"])
    return out


def build_team_map_records(matches: list[dict]) -> list[dict]:
    """teamMapRecords: per-team win/loss per map, from DECIDED maps only. An
    undecided map appears in `undecided` rather than being counted as a loss."""
    teams: dict[str, dict] = {}
    for m in matches:
        for g in m.get("maps") or []:
            for team, opponent in ((m.get("teamA"), m.get("teamB")),
                                   (m.get("teamB"), m.get("teamA"))):
                if not team or not g.get("map"):
                    continue
                t = teams.setdefault(team, {"teamId": team, "maps": {}})
                row = t["maps"].setdefault(g["map"], {
                    "map": g["map"], "mode": g.get("mode"), "wins": 0,
                    "losses": 0, "undecided": 0, "matchIds": []})
                if m["id"] not in row["matchIds"]:
                    row["matchIds"].append(m["id"])
                if not g.get("winner"):
                    row["undecided"] += 1
                elif g["winner"] == team:
                    row["wins"] += 1
                else:
                    row["losses"] += 1
                _ = opponent
    out = []
    for t in teams.values():
        rows = []
        for row in t["maps"].values():
            decided = row["wins"] + row["losses"]
            rows.append(dict(row, played=decided + row["undecided"],
                             winRate=(round(row["wins"] / decided, 5)
                                      if decided else None)))
        rows.sort(key=lambda r: (-r["played"], r["map"]))
        out.append({"teamId": t["teamId"], "maps": rows})
    out.sort(key=lambda t: t["teamId"])
    return out


def build_map_mode_stats(matches: list[dict],
                         maps_catalog: list[dict]) -> tuple[list, list]:
    """(mapStats, modeStats): how much verified play each map and each mode
    actually has. These are the numbers that make coverage gaps visible —
    a map with 0 plays should read as 0, never be omitted."""
    mode_of = {c["id"]: c.get("mode") for c in maps_catalog}
    per_map: dict[str, dict] = {c["id"]: {
        "map": c["id"], "name": c["name"], "mode": c.get("mode"),
        "played": 0, "decided": 0, "matchIds": [], "roundCount": 0}
        for c in maps_catalog}
    for m in matches:
        for g in m.get("maps") or []:
            mid = g.get("map")
            if not mid:
                continue
            row = per_map.setdefault(mid, {
                "map": mid, "name": mid, "mode": mode_of.get(mid),
                "played": 0, "decided": 0, "matchIds": [], "roundCount": 0})
            row["played"] += 1
            row["roundCount"] += int(g.get("roundCount") or 0)
            if g.get("winner"):
                row["decided"] += 1
            if m["id"] not in row["matchIds"]:
                row["matchIds"].append(m["id"])
    map_stats = sorted(per_map.values(),
                       key=lambda r: (-r["played"], r["map"]))
    modes: dict[str, dict] = {}
    for row in map_stats:
        mode = row["mode"] or "Unknown"
        mo = modes.setdefault(mode, {"mode": mode, "maps": 0, "mapsPlayed": 0,
                                     "played": 0, "decided": 0})
        mo["maps"] += 1
        mo["played"] += row["played"]
        mo["decided"] += row["decided"]
        if row["played"]:
            mo["mapsPlayed"] += 1
    mode_stats = sorted(modes.values(), key=lambda r: (-r["played"], r["mode"]))
    return map_stats, mode_stats


# --------------------------------------------------- provisional blocking
def provisional_reasons(con, match_id: str) -> list[str]:
    """Why a match must NOT reach the public site yet, if any.

    A "provisional" match is one carrying CV output that no human has signed
    off. The export already only reads `ingest_runs` with status='complete'
    and only emits comp snapshots in an approved review state — this function
    is the explicit, testable statement of that rule, and it closes the two
    ways a provisional row could still slip through:

      * an ingest run that exists but is not complete (a dry run, a crash, a
        detection awaiting review) — its map must publish no compositions;
      * a match flagged `needs_review` / a non-final lifecycle while carrying
        map results.

    Returns [] when the match is safe to publish.
    """
    reasons: list[str] = []
    runs = list(con.execute(
        "SELECT id, status FROM ingest_runs WHERE match_id=?", (match_id,)))
    incomplete = [r["id"] for r in runs if (r["status"] or "") != "complete"]
    if incomplete:
        reasons.append(
            f"ingest run(s) {', '.join(incomplete)} are not complete — their "
            f"detections have not been reviewed and committed")
    row = con.execute("SELECT * FROM matches WHERE id=?", (match_id,)).fetchone()
    if row is None:
        reasons.append(f"match {match_id} does not exist in the content DB")
        return reasons
    cols = row.keys()
    if "needs_review" in cols and rv(row, "needs_review"):
        reasons.append("match is flagged needs_review")
    return reasons


# --------------------------------------------------------- official calendar
# The season's EVENT structure (regional stage windows, major events, their
# official broadcast destinations) lives in config/owcs_calendar.json and was
# reaching the automation DB's `source_events` ledger and stopping there —
# nothing exported it, so the public calendar could only ever show matches
# that had already been ingested. It had no idea a stage was even running.
#
# Exported straight from the committed config (not the automation DB) on
# purpose: the config is the source of truth, it is offline, and the public
# build must not require the operator's private job database.
CALENDAR_CONFIG = os.path.join(db.REPO_ROOT, "config", "owcs_calendar.json")


def build_calendar_events(path: str = CALENDAR_CONFIG) -> list[dict]:
    """Official-calendar events for the public dataset.

    `verified` is carried through UNCHANGED. Every event in the committed
    seed is currently `verified: false` (the official schedule site was not
    reachable when it was written), and the site is required to say so
    rather than present placeholder dates as fact.
    """
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = json.load(f)
    except (OSError, ValueError):
        return []
    out = []
    for e in raw.get("events", []) or []:
        eid = e.get("id")
        if not eid or not e.get("startDate"):
            continue        # an event with no id or no start cannot be placed
        out.append({
            "id": eid,
            "name": e.get("name") or eid,
            "region": (e.get("region") or "global").lower(),
            "stage": e.get("stage"),
            "startDate": e.get("startDate"),
            "endDate": e.get("endDate") or e.get("startDate"),
            "verified": bool(e.get("verified")),
            "broadcastChannels": list(e.get("broadcastChannels") or []),
            "faceitCompetitionId": e.get("faceitCompetitionId"),
        })
    out.sort(key=lambda e: (e["startDate"], e["id"]))
    return out


def build_public_payload(con) -> dict:
    """The production public.v1 dataset, built ONLY from reviewed/staged
    DB state: matches, map_results, hero_stints (approved statuses),
    hero_swaps, ingest_runs. Nothing is invented; missing facts stay null
    with honest notes."""
    now = dt.datetime.now(dt.timezone.utc).isoformat()
    heroes = attach_portraits(
        [{"id": r["id"], "name": r["name"], "role": r["role"]}
         for r in con.execute("SELECT * FROM heroes ORDER BY role, name")])
    maps_catalog = [{"id": r["id"], "name": r["name"], "mode": r["mode"]}
                    for r in con.execute(
                        "SELECT * FROM game_maps ORDER BY name")]

    roster_size = con.execute("SELECT COUNT(*) FROM heroes").fetchone()[0]
    ingest_rows = con.execute(
        "SELECT * FROM ingest_runs WHERE status='complete'").fetchall()
    match_ids = sorted({r["match_id"] for r in ingest_rows
                        if r["match_id"]})
    hero_bans_out: list[dict] = []

    teams_needed: set[str] = set()
    matches_out, runs_out, snaps_out, players_out = [], [], [], []
    swaps_out: list[dict] = []
    # Phase 7 contract: the hero-stint timeline itself, not only the comp
    # snapshots derived from it. Only APPROVED stints are emitted — the same
    # 'auto-high'/'reviewed' gate every other public number uses.
    hero_stints_out: list[dict] = []
    vod_out: dict[str, dict] = {}
    tournaments_by_id: dict[str, dict] = {}

    for mid in match_ids:
        m = con.execute("SELECT * FROM matches WHERE id=?",
                        (mid,)).fetchone()
        if m is None:
            continue
        teams_needed.update((m["team_a"], m["team_b"]))
        tid = _tournament_id(m)
        maps_out = []
        for mr in con.execute(
                """SELECT * FROM map_results WHERE match_id=?
                   ORDER BY map_order""", (mid,)).fetchall():
            rounds = con.execute(
                """SELECT * FROM map_rounds WHERE map_result_id=?
                   ORDER BY round_index""", (mr["id"],)).fetchall()
            stints = _stints_for_map(con, mr["id"])
            map_pub_id_for_stints = f"{mid}-m{mr['map_order']}"
            for st in stints:
                if rv(st, "status") not in APPROVED_REVIEW_STATES:
                    continue
                evs, eve = rv(st, "evidence_start"), rv(st, "evidence_end")
                hero_stints_out.append({
                    "id": (f"hs-{map_pub_id_for_stints}-{st['team_id']}-"
                           f"{st['slot']}-{st['start_offset']}"),
                    "matchId": mid, "mapId": map_pub_id_for_stints,
                    "teamId": st["team_id"], "side": rv(st, "side"),
                    "slot": rv(st, "slot"), "hero": st["hero_id"],
                    "start": rv(st, "start_offset"), "end": rv(st, "end_offset"),
                    "observations": rv(st, "n_obs"),
                    "meanConfidence": rv(st, "mean_conf"),
                    "minConfidence": rv(st, "min_conf"),
                    "reviewStatus": rv(st, "status"),
                    "source": ("manual" if rv(st, "manual_override") else
                               rv(st, "source", "cv")),
                    "detectorVersion": rv(st, "detector_version"),
                    "evidenceStart": evs if evs and os.path.exists(
                        os.path.join(db.REPO_ROOT, evs)) else None,
                    "evidenceEnd": eve if eve and os.path.exists(
                        os.path.join(db.REPO_ROOT, eve)) else None,
                    "ingestId": rv(st, "ingest_id"),
                })
            run = next((r for r in ingest_rows
                        if r["match_id"] == mid
                        and r["map_order"] == mr["map_order"]), None)
            map_pub_id = f"{mid}-m{mr['map_order']}"
            mode = next((c["mode"] for c in maps_catalog
                         if c["id"] == mr["map_id"]), None)
            maps_out.append({
                "id": map_pub_id,
                "order": mr["map_order"],
                "map": mr["map_id"],
                "mode": mode,
                "winner": rv(mr, "winner_team"),
                "scoreA": rv(mr, "score_a"),
                "scoreB": rv(mr, "score_b"),
                # per-round capture % is not measured by the CV pipeline
                # yet -> null means the page renders its honest fallback.
                # roundCount IS real (segmented by the round-emblem detector)
                # — the honest first step toward per-submap detail.
                "scoreDetail": None,
                "roundCount": len(rounds),
                # real round windows from the round-emblem detector —
                # broadcast offsets in seconds, ±1 sample (~5 s).
                "rounds": [{"index": r_["round_index"],
                            "start": rv(r_, "start_offset"),
                            "end": rv(r_, "end_offset"),
                            "confidence": rv(r_, "confidence"),
                            "source": rv(r_, "source", "cv")}
                           for r_ in rounds],
                "pickedBy": rv(mr, "picked_by_team"),
                "pickNote": None,
            })
            # hero swaps for this map — the temporal-consensus verdicts,
            # confirmed AND rejected. Confirmed rows carry before/after
            # evidence crops; rejected rows carry the honest reason they
            # were thrown out. Nothing here is invented.
            for s in con.execute(
                    """SELECT * FROM hero_swaps WHERE map_result_id=?
                       ORDER BY offset_seconds""", (mr["id"],)):
                evb, eva = rv(s, "evidence_before"), rv(s, "evidence_after")
                swaps_out.append({
                    "id": f"sw-{map_pub_id}-{s['team_id']}-{s['slot']}-"
                          f"{s['offset_seconds']}-{s['status']}",
                    "matchId": mid,
                    "mapId": map_pub_id,
                    "teamId": s["team_id"],
                    "side": rv(s, "side"),
                    "slot": rv(s, "slot"),
                    "fromHero": s["from_hero"],
                    "toHero": s["to_hero"],
                    "offset": rv(s, "offset_seconds"),
                    "confidence": rv(s, "confidence"),
                    "status": s["status"],
                    "reason": rv(s, "reason"),
                    "evidenceBefore": evb if evb and os.path.exists(
                        os.path.join(db.REPO_ROOT, evb)) else None,
                    "evidenceAfter": eva if eva and os.path.exists(
                        os.path.join(db.REPO_ROOT, eva)) else None,
                    "ingestId": rv(s, "ingest_id"),
                })
            # hero bans for this map (real match facts; empty when the
            # broadcast/import recorded none — the UI says so honestly).
            for b in con.execute(
                    """SELECT * FROM hero_bans WHERE match_id=?
                       AND (map_result_id=? OR map_result_id IS NULL)
                       ORDER BY COALESCE(ban_order, id)""",
                    (mid, mr["id"])):
                hero_bans_out.append({
                    "id": f"ban-{map_pub_id}-{b['hero_id']}-{rv(b, 'team_id') or 'x'}",
                    "matchId": mid,
                    "mapId": map_pub_id,
                    "hero": b["hero_id"],
                    "teamId": rv(b, "team_id"),
                    "source": rv(b, "source", "manual"),
                })
            if run is None:
                continue
            frames_rel = f"reports/ingest/{run['id']}/frames"
            approved = {"auto-high", "reviewed"}
            for team in (m["team_a"], m["team_b"]):
                for t in _snapshot_times(con, mr["id"], team, rounds):
                    heroes5, rows = _comp_at(stints, team, t)
                    if len(heroes5) != 5:
                        continue
                    statuses = {r_["status"] for r_ in rows}
                    review = ("auto-high" if statuses <= approved
                              else "needs-review")
                    manual = any(rv(r_, "manual_override") for r_ in rows)
                    confs = [rv(r_, "mean_conf") for r_ in rows
                             if rv(r_, "mean_conf") is not None]
                    side = rows[0]["side"] if rows else None
                    snaps_out.append({
                        "id": f"cs-{map_pub_id}-{team}-{t}",
                        "matchId": mid,
                        "mapId": map_pub_id,
                        "teamId": team,
                        "side": side,
                        "timestamp": t,
                        "heroes": heroes5,
                        "source": "manual" if manual else "cv",
                        "confidence": (round(sum(confs) / len(confs), 3)
                                       if confs else None),
                        "reviewStatus": review,
                        "evidenceRunId": run["id"],
                        "evidenceFrame": _nearest_frame(frames_rel, t),
                    })

        run_ids = [r["id"] for r in ingest_rows if r["match_id"] == mid]
        for r in ingest_rows:
            if r["match_id"] != mid:
                continue
            frames_rel = f"reports/ingest/{r['id']}/frames"
            frames = []
            fdir = os.path.join(db.REPO_ROOT, frames_rel)
            if os.path.isdir(fdir):
                for fn in sorted(os.listdir(fdir)):
                    if fn.startswith("frame_"):
                        try:
                            off = int(fn.split("_")[1].split(".")[0])
                        except ValueError:
                            continue
                        frames.append({"offset": off,
                                       "file": f"{frames_rel}/{fn}",
                                       "layoutDebug": None})
            crops = []
            for s in con.execute(
                    """SELECT evidence_before, evidence_after
                       FROM hero_swaps WHERE ingest_id=?
                       AND status='confirmed'""", (r["id"],)):
                for c in (s["evidence_before"], s["evidence_after"]):
                    if c and os.path.exists(os.path.join(db.REPO_ROOT, c)):
                        crops.append(c)
            runs_out.append({
                "id": r["id"],
                "matchId": mid,
                "sourceId": rv(r, "source_id"),
                "window": {"start": _fmt_clock(rv(r, "start_offset")),
                           "end": _fmt_clock(rv(r, "end_offset")),
                           "every": 5},
                "requestedHeight": 720,
                "actualWidth": 1280,
                "actualHeight": 720,
                "clipMode": "direct-url-cut",
                "status": "needs-review",
                "reportPath": rv(r, "report_path"),
                "createdAt": rv(r, "created_at"),
                "frames": frames,
                "crops": crops,
                "note": ("full-map CV ingestion "
                         f"({rv(r, 'detector_version')}, calibration "
                         f"{rv(r, 'calibration_version')})"),
                # autocalibration provenance for the 'trust this footage'
                # story — real numbers from the source's layout, or null.
                "calibration": calibration_summary(
                    rv(r, "source_id"), roster_size),
                "calibrationStatus": rv(r, "calibration_status", "ok"),
                "calibrationVersion": rv(r, "calibration_version"),
            })

        for p in con.execute(
                """SELECT r.team_id, p.* FROM match_rosters r
                   JOIN players p ON p.id=r.player_id
                   WHERE r.match_id=? AND COALESCE(p.source,'') <> ?""",
                (mid, SAMPLE_PLAYER_SOURCE)):
            players_out.append({"id": p["id"], "teamId": p["team_id"],
                                "handle": p["nickname"],
                                "role": rv(p, "role")})

        vurl = rv(m, "vod_url")
        if vurl:
            vod_out[vurl] = {
                "id": rv(m, "source_ref") or f"vod-{mid}",
                "provider": "youtube",
                "url": vurl,
                "title": rv(m, "event_name") or "OWCS broadcast VOD",
                "matchIds": [mid],
                "heightAvailable": 1080,
            }

        stage_name = rv(m, "stage") or "Matches"
        matches_out.append({
            "id": mid,
            "tournamentId": tid,
            "stageId": f"{tid}-stage",
            "roundId": None,
            "teamA": m["team_a"],
            "teamB": m["team_b"],
            "bestOf": 5,
            # `scheduled_at` is a real start instant; `date` is a day with no
            # time. Deriving midnight from a date and publishing it as
            # `scheduledAt` is fine for placing the match on a calendar, but
            # the UI must not render 00:00 UTC as if it were a kickoff time —
            # hence the explicit flag rather than a magic-value convention.
            "scheduledAt": (rv(m, "scheduled_at")
                            or f"{m['date']}T00:00:00+00:00"),
            "timeKnown": bool(rv(m, "scheduled_at")),
            "status": "completed",
            "scoreA": rv(m, "score_a") or None,
            "scoreB": rv(m, "score_b") or None,
            "winner": rv(m, "winner_team"),
            "streamUrl": vurl,
            "faceitUrl": rv(m, "faceit_room_url"),
            "liquipediaUrl": None,
            "casters": [],
            "sources": [{"type": "vod", "url": vurl,
                         "lastSynced": now}] if vurl else [],
            "captureStatus": "needs-review",
            "captureRunId": run_ids[0] if run_ids else None,
            "summary": (f"{len(maps_out)} map(s) captured and ingested by "
                        "the CV pipeline; series score not yet recorded — "
                        "only verified data is shown."),
            "maps": maps_out,
        })

        if tid not in tournaments_by_id:
            tournaments_by_id[tid] = {
                "id": tid,
                "name": rv(m, "event_name") or "OWCS 2026",
                "series": "OWCS",
                "region": _region_id(rv(m, "region")),
                "tier": "S",
                "year": 2026,
                "startsAt": f"{m['date']}T00:00:00+00:00",
                "endsAt": None,
                "status": "completed",
                "prizePool": None,
                "teamIds": set(),
                "winnerTeamId": None,
                "summary": (f"{stage_name}. Matches appear here as their "
                            "VODs are captured and reviewed."),
                "logoUrl": None,
                "sources": [],
                "stages": [{"id": f"{tid}-stage", "name": stage_name,
                            "order": 1, "format": "Double elimination",
                            "status": "completed"}],
                "standings": [],
            }
        tourn = tournaments_by_id[tid]
        tourn["teamIds"].update((m["team_a"], m["team_b"]))
        if vurl and not any(s["url"] == vurl for s in tourn["sources"]):
            tourn["sources"].append({"type": "vod", "url": vurl,
                                     "lastSynced": now})

    # ---- Phase B: discovered scheduled matches (facts before CV) ----------
    # A match can publish its calendar facts before its compositions are
    # processed (roadmap I3). Any content-DB match in the rolling discovery
    # window that hasn't already been emitted from a CV run is added here with
    # its real scheduled time and an honest capture state, so calendar.html
    # populates the moment FACEIT discovery upserts a match — no comps invented.
    emitted_ids = {mo["id"] for mo in matches_out}
    # Tournaments invented as stubs below start life as "upcoming" because a
    # freshly discovered match carries no event lifecycle of its own. That
    # guess has to be reconciled against the matches once they are all known
    # (see the _reconcile_stub_tournament_status pass after this loop) —
    # otherwise a finished event keeps advertising itself as upcoming.
    stub_tids: set = set()
    for m in _discovered_window_matches(con):
        if m["id"] in emitted_ids:
            continue
        tid = _tournament_id(m)
        vurl = rv(m, "vod_url")
        has_maps = con.execute(
            "SELECT 1 FROM map_results WHERE match_id=? LIMIT 1", (m["id"],)
        ).fetchone() is not None
        teams_needed.update((m["team_a"], m["team_b"]))
        matches_out.append({
            "id": m["id"],
            "tournamentId": tid,
            "stageId": f"{tid}-stage",
            "roundId": None,
            "teamA": m["team_a"],
            "teamB": m["team_b"],
            "bestOf": 5,
            "scheduledAt": (rv(m, "scheduled_at")
                            or f"{m['date']}T00:00:00+00:00"),
            # See the note on the other match builder: midnight derived from
            # a bare date must never render as a real kickoff time.
            "timeKnown": bool(rv(m, "scheduled_at")),
            "status": _public_match_status(m),
            "scoreA": rv(m, "score_a") or None,
            "scoreB": rv(m, "score_b") or None,
            "winner": rv(m, "winner_team"),
            "streamUrl": vurl,
            "faceitUrl": rv(m, "faceit_room_url"),
            "liquipediaUrl": None,
            "casters": [],
            "sources": ([{"type": "vod", "url": vurl, "lastSynced": now}]
                        if vurl else []),
            "captureStatus": _public_capture_status(m, bool(vurl), has_maps),
            "captureRunId": None,
            "summary": ("Discovered from FACEIT; calendar facts only — "
                        "compositions are not yet processed."),
            "maps": [],
        })
        if tid not in tournaments_by_id:
            stub_tids.add(tid)
            stage_name = rv(m, "stage") or "Matches"
            tournaments_by_id[tid] = {
                "id": tid, "name": rv(m, "event_name") or "OWCS 2026",
                "series": "OWCS", "region": _region_id(rv(m, "region")),
                "tier": "S", "year": 2026,
                "startsAt": f"{m['date']}T00:00:00+00:00", "endsAt": None,
                "status": "upcoming", "prizePool": None,
                "teamIds": set(), "winnerTeamId": None,
                "summary": f"{stage_name}. Discovered via FACEIT sync.",
                "logoUrl": None, "sources": [],
                "stages": [{"id": f"{tid}-stage", "name": stage_name,
                            "order": 1, "format": "Double elimination",
                            "status": "upcoming"}],
                "standings": [],
            }
        tournaments_by_id[tid]["teamIds"].update((m["team_a"], m["team_b"]))

    _reconcile_stub_tournament_status(tournaments_by_id, stub_tids, matches_out)

    tournaments_out = [dict(t, teamIds=sorted(t["teamIds"]))
                       for t in tournaments_by_id.values()]

    # Phase D2: every team in the canonical registry is a public entity,
    # independent of whether the vision pipeline has captured any of its
    # maps yet (teams_needed above still scopes tournament rosters/logos
    # elsewhere; it never gates WHICH teams the site knows about).
    asset_sources = _team_asset_sources()
    # hero_stints is the REAL, current full-map CV pipeline's output (the
    # Nepal milestone lives here); comp_snapshots is an older, separate
    # capture path still written by other tools but not what the public
    # compSnapshots payload above is actually built from — using it here
    # would call a team's tracking "pending" or "done" on the wrong signal.
    captured_team_ids = {r["team_id"] for r in con.execute(
        "SELECT DISTINCT team_id FROM hero_stints")} if _has_table(con, "hero_stints") else set()
    teams = [{"id": r["id"], "name": r["name"], "code": r["code"],
              "region": _region_id(rv(r, "region")),
              "logoUrl": rv(r, "logo_url"),
              # Team profile enrichment (Phase D) — FACEIT facts only, never
              # a logo (logoUrl above stays the human-verified asset alone).
              "description": rv(r, "description"),
              "website": rv(r, "website"),
              "socials": {k: v for k, v in
                          {"twitter": rv(r, "twitter"), "facebook": rv(r, "facebook")}.items()
                          if v} or None,
              "memberCount": rv(r, "member_count"),
              # Canonical team registry (Phase D2) — identity/roster facts
              # and explicit coverage states; never a substitute for actual
              # capture evidence (compositionTrackingPending says so plainly).
              "status": rv(r, "status", "active"),
              "organization": rv(r, "organization"),
              "aliases": _json_list(rv(r, "aliases")),
              "previousNames": _json_list(rv(r, "previous_names")),
              "sourceAuthority": rv(r, "source_authority"),
              "identityVerifiedAt": rv(r, "identity_verified_at"),
              "rosterSource": rv(r, "roster_source"),
              "rosterVerifiedAt": rv(r, "roster_verified_at"),
              "roster": _current_roster(con, r["id"]),
              "needsReview": bool(rv(r, "needs_review")),
              "reviewReason": rv(r, "review_reason"),
              "hasLogoCandidate": _has_logo_candidate(r["id"], asset_sources),
              "compositionTrackingPending": r["id"] not in captured_team_ids}
             for r in con.execute("SELECT * FROM teams ORDER BY name")]

    # ---- provisional blocking (Phase 7) ---------------------------------
    # A match carrying unreviewed CV output must not reach the public site.
    # Its calendar facts (teams, schedule, status) are safe and stay; its
    # MAPS and every composition/swap/ban derived from them are withheld,
    # with the reason recorded in meta so the withholding is visible rather
    # than looking like missing data.
    blocked: list[dict] = []
    for mo in matches_out:
        reasons = provisional_reasons(con, mo["id"])
        if not reasons:
            continue
        blocked.append({"matchId": mo["id"], "reasons": reasons})
        mo["maps"] = []
        mo["captureStatus"] = "needs-review"
        mo["summary"] = ("Withheld from publication: "
                         + "; ".join(reasons)
                         + ". Calendar facts only — no composition, swap or "
                           "score from this match is published until review "
                           "is complete.")
    blocked_ids = {b["matchId"] for b in blocked}
    if blocked_ids:
        snaps_out = [s for s in snaps_out if s["matchId"] not in blocked_ids]
        swaps_out = [s for s in swaps_out if s["matchId"] not in blocked_ids]
        hero_bans_out = [b for b in hero_bans_out
                         if b["matchId"] not in blocked_ids]
        runs_out = [r for r in runs_out if r["matchId"] not in blocked_ids]
        hero_stints_out = [s_ for s_ in hero_stints_out
                           if s_["matchId"] not in blocked_ids]

    # ---- derived aggregates (Phase 7) -----------------------------------
    # Computed AFTER provisional blocking, from exactly the rows that will
    # actually ship, so no aggregate can ever include a withheld match.
    comp_frequency, comp_win_rate = build_comp_stats(snaps_out, matches_out)
    hero_rates = build_hero_rates(snaps_out, swaps_out, matches_out)
    team_pools = build_team_hero_pools(snaps_out, matches_out)
    team_map_records = build_team_map_records(matches_out)
    map_stats, mode_stats = build_map_mode_stats(matches_out, maps_catalog)

    return {
        "meta": {
            "schema": "public.v1",
            "demo": False,
            "generatedAt": now,
            "note": ("Production export from data/owcs.sqlite — only "
                     "captured, staged and reviewed data; no invented "
                     "values."),
            # Publication provenance: what was withheld and why, so a gap on
            # the site is always explainable from the export itself.
            "withheldMatches": blocked,
            "withheldCount": len(blocked),
            "approvedReviewStates": list(APPROVED_REVIEW_STATES),
            "aggregatesNote": ("compFrequency/compWinRate/heroPickRates/"
                               "teamHeroPools/teamMapRecords/mapStats/"
                               "modeStats are derived from the approved comp "
                               "snapshots in THIS file, after provisional "
                               "matches were withheld — they can never "
                               "include a withheld match."),
        },
        "regions": REGIONS,
        "teams": teams,
        "players": players_out,
        "tournaments": tournaments_out,
        # The official season structure — stage windows and their broadcast
        # destinations. Carries `verified` unchanged so the calendar can be
        # explicit about which dates are confirmed and which are a seed.
        "calendarEvents": build_calendar_events(),
        "bracketRounds": [],
        "extraRounds": [],
        "bracketMatches": [],
        "matches": matches_out,
        "mapResults": [dict(g, matchId=mo["id"])
                       for mo in matches_out for g in (mo.get("maps") or [])],
        "heroBans": hero_bans_out,
        "heroSwaps": swaps_out,
        "rejectedSwaps": [s for s in swaps_out if s.get("status") != "confirmed"],
        "heroStints": hero_stints_out,
        "captureRuns": runs_out,
        "compSnapshots": snaps_out,
        "vodSources": list(vod_out.values()),
        "heroes": heroes,
        "mapsCatalog": maps_catalog,
        "patches": [],
        # ---- derived aggregates -----------------------------------------
        "compFrequency": comp_frequency,
        "compWinRate": comp_win_rate,
        "heroPickRates": hero_rates,
        "teamHeroPools": team_pools,
        "teamMapRecords": team_map_records,
        "mapStats": map_stats,
        "modeStats": mode_stats,
    }


def _stamp() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M")


def render_main_body(payload: dict, ts: str | None = None) -> str:
    """The exact bytes of assets/js/data.js for `payload`.

    Single source of truth so every writer (this module and
    pipeline/run_batch.py) emits a byte-identical file. run_batch used to
    inline its own `json.dumps(payload, indent=1)` WITHOUT
    `ensure_ascii=False`, so a batch run rewrote every non-ASCII team and
    player name as a `\\uXXXX` escape — a whole-file diff against the
    export this module produces, for identical data.
    """
    return (HEADER.format(ts=ts or _stamp())
            + json.dumps(payload, indent=1, ensure_ascii=False) + ";\n")


def render_public_body(payload: dict, ts: str | None = None) -> str:
    """The exact bytes of assets/data/public_data.v1.js for `payload`."""
    return (PUBLIC_HEADER.format(ts=ts or _stamp())
            + json.dumps(payload, indent=1, ensure_ascii=False) + ";\n")


def write_body(path: str, body: str) -> None:
    """Write a generated export deterministically on every platform.

    `newline=""` disables Python's universal-newline translation: without
    it a Windows run turns every "\\n" in `body` into "\\r\\n", so the file
    an operator generates on Windows is byte-different from the one CI
    generates on Linux even when the data is identical.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(body)


# The generation timestamp is the ONE thing that legitimately differs
# between two exports of the same database: it appears in the banner
# comment, in meta.generatedAt, and (as the same ISO string) in every
# source's `lastSynced`. Nothing else may differ.
_HEADER_TS_RE = re.compile(
    r"(GENERATED by pipeline/export_data\.py[^\n]*? on )"
    r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}( UTC)")
_GENERATED_AT_RE = re.compile(r'"generatedAt":\s*"([^"]+)"')
_TS_PLACEHOLDER = "<GENERATED-AT>"


def normalize_generated(body: str) -> str:
    """Blank out only the generation timestamp, so two exports of the same
    DB compare equal. CRLF is folded to LF first so a Windows checkout
    (or a `core.autocrlf` clone) does not read as drift."""
    body = body.replace("\r\n", "\n")
    body = _HEADER_TS_RE.sub(r"\g<1>" + _TS_PLACEHOLDER + r"\g<2>", body)
    m = _GENERATED_AT_RE.search(body)
    if m and m.group(1):
        body = body.replace(m.group(1), _TS_PLACEHOLDER)
    return body


def check_reproducible(con, public: bool = False) -> int:
    """Fail loudly when a committed export no longer matches the database.

    This is the gate ci.yml runs. It deliberately does NOT write anything:
    regenerating in place left the working tree dirty, which made
    test_release_reproducibility's "the suite leaves the tree clean" guard
    skip itself on every CI run.
    """
    targets: list[tuple[str, str]] = [
        (OUT_PATH, render_main_body(build_payload(con)))]
    if public:
        targets.append(
            (PUBLIC_OUT_PATH, render_public_body(build_public_payload(con))))

    problems: list[str] = []
    for path, fresh in targets:
        rel = os.path.relpath(path, db.REPO_ROOT).replace(os.sep, "/")
        if not os.path.exists(path):
            problems.append(f"{rel}: MISSING — nothing to compare against; "
                            f"run the exporter and commit the result")
            continue
        with open(path, encoding="utf-8", newline="") as f:
            committed = f.read()
        a = normalize_generated(committed)
        b = normalize_generated(fresh)
        if a == b:
            print(f"REPRODUCIBLE  {rel} (matches a fresh export from "
                  f"data/owcs.sqlite; timestamp aside)")
            continue
        diff = difflib.unified_diff(
            a.splitlines(), b.splitlines(),
            fromfile=f"{rel} (committed)", tofile=f"{rel} (fresh export)",
            lineterm="", n=2)
        excerpt = "\n".join(itertools.islice(diff, 120))
        problems.append(
            f"{rel}: DRIFT — the committed file is not what "
            f"pipeline/export_data.py produces from data/owcs.sqlite today. "
            f"Re-export and commit the result.\n{excerpt}")

    if problems:
        print("\nEXPORT REPRODUCIBILITY CHECK FAILED:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    return 0


def write_public(con) -> str:
    payload = build_public_payload(con)
    write_body(PUBLIC_OUT_PATH, render_public_body(payload))
    print(f"Wrote {PUBLIC_OUT_PATH}: {len(payload['matches'])} matches, "
          f"{len(payload['compSnapshots'])} comp snapshots, "
          f"{len(payload['captureRuns'])} capture runs.")
    return PUBLIC_OUT_PATH


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stdout", action="store_true",
                    help="print JSON instead of writing data.js")
    ap.add_argument("--public", action="store_true",
                    help="ALSO write assets/data/public_data.v1.js "
                         "(production public dataset)")
    ap.add_argument("--check", action="store_true",
                    help="write NOTHING; verify the committed export(s) "
                         "still match a fresh export from data/owcs.sqlite "
                         "(generation timestamp aside). Exit 1 on drift. "
                         "Combine with --public to check both files.")
    args = ap.parse_args()

    con = db.connect()

    if args.check:
        return check_reproducible(con, public=args.public)

    payload = build_payload(con)

    if args.stdout:
        json.dump(payload, sys.stdout, indent=1)
        return 0

    write_body(OUT_PATH, render_main_body(payload))
    bans = sum(len(g["faceit"]["heroBans"]) for m_ in payload["matches"] for g in m_["maps"])
    detected = sum(1 for m_ in payload["matches"] for g in m_["maps"] if g["tracker"]["detected"])
    total = sum(len(m_["maps"]) for m_ in payload["matches"])
    print(f"Wrote {OUT_PATH}: {len(payload['matches'])} matches, "
          f"{total} maps ({detected} with tracker comps, "
          f"{total - detected} FACEIT-only), {bans} hero bans.")
    if args.public:
        write_public(con)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
