#!/usr/bin/env python3
"""
export_data.py — publish the SQLite database to the static website.

Reads data/owcs.sqlite and writes assets/js/data.js as window.OWCS_DATA.
Milestone 1 exports both completed comp data and partial FACEIT matchroom
metadata, so the frontend can show useful map order, bans, replay codes, and
empty states before computer vision has processed a match.

Usage:
  python3 pipeline/export_data.py            # writes assets/js/data.js
  python3 pipeline/export_data.py --stdout   # print JSON to stdout instead
"""
from __future__ import annotations
import argparse
import datetime as dt
import json
import os
import sys
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db  # noqa: E402

OUT_PATH = os.path.join(db.REPO_ROOT, "assets", "js", "data.js")
SOURCES_PATH = os.path.join(db.REPO_ROOT, "data", "sources",
                            "video_sources.json")


def load_video_sources(path: str = SOURCES_PATH) -> list[dict]:
    """Metadata-only view of video_sources.json for the static site."""
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            entries = json.load(f).get("sources", []) or []
    except (ValueError, OSError):
        return []
    out = []
    for s in entries:
        sid = s.get("id") or s.get("match")
        if not sid:
            continue
        out.append({
            "id": sid,
            "title": s.get("title") or sid,
            "url": s.get("url") or s.get("vodUrl"),
            "platform": s.get("platform") or ("demo" if s.get("fixtureFrames") else "unknown"),
            "date": s.get("date"),
            "region": s.get("region"),
            "enabled": s.get("enabled", True),
            "layout": s.get("layout"),
            "mode": s.get("mode"),
            "notes": s.get("notes"),
        })
    return out

PORTRAIT_DIR = os.path.join(db.REPO_ROOT, "assets", "img", "heroes")


def hero_portraits() -> dict[str, str]:
    """{hero_id: site-relative url} for every hero with a REAL broadcast
    portrait (generated by pipeline/build_hero_portraits.py from harvested
    template crops). Heroes without one fall back to monogram tiles."""
    out: dict[str, str] = {}
    if os.path.isdir(PORTRAIT_DIR):
        for fn in sorted(os.listdir(PORTRAIT_DIR)):
            if fn.endswith(".png"):
                out[fn[:-4]] = f"assets/img/heroes/{fn}"
    return out


def attach_portraits(heroes: list[dict]) -> list[dict]:
    ports = hero_portraits()
    for h in heroes:
        if h["id"] in ports:
            h["portraitUrl"] = ports[h["id"]]
    return heroes


HEADER = """/* =====================================================================
   OWCS Comp Tracker — data.js
   GENERATED by pipeline/export_data.py on {ts} UTC — do not hand-edit.
   ===================================================================== */

window.OWCS_DATA = """


def rv(row: Any, key: str, default: Any = None) -> Any:
    """sqlite3.Row safe getter that also tolerates older DBs."""
    if row is None:
        return default
    try:
        return row[key]
    except Exception:
        return default


def snapshot_comp(con, snapshot_id: int) -> list[str]:
    return [r["hero_id"] for r in con.execute(
        "SELECT hero_id FROM snapshot_heroes WHERE snapshot_id=? ORDER BY slot",
        (snapshot_id,),
    ).fetchall()]


def comp_info_for_map(con, map_result_id: int, team_id: str) -> dict:
    """Union of heroes seen for this team on this map, ordered by the best
    snapshot's slots first. Opener is the earliest snapshot. Swap heroes are
    anything seen beyond the first five opener heroes."""
    snaps = con.execute(
        """SELECT id, overall_confidence, stream_offset_seconds,
                  COALESCE(source,'cv') AS source
           FROM comp_snapshots
           WHERE map_result_id=? AND team_id=?
           ORDER BY stream_offset_seconds ASC, id ASC""",
        (map_result_id, team_id),
    ).fetchall()
    # Manual corrections override every other source outright.
    manual = [s_ for s_ in snaps if s_["source"] == "manual"]
    if manual:
        snaps = manual
    if not snaps:
        return {"comp": [], "opener": [], "swaps": [], "confidence": None}

    opener = snapshot_comp(con, snaps[0]["id"])
    best = sorted(snaps, key=lambda s: (rv(s, "overall_confidence", 0) or 0), reverse=True)[0]
    comp: list[str] = []
    for hid in snapshot_comp(con, best["id"]):
        if hid not in comp:
            comp.append(hid)
    for s in snaps:
        for hid in snapshot_comp(con, s["id"]):
            if hid not in comp:
                comp.append(hid)
    confidence_values = [rv(s, "overall_confidence") for s in snaps if rv(s, "overall_confidence") is not None]
    confidence = round(sum(confidence_values) / len(confidence_values), 3) if confidence_values else None
    return {
        "comp": comp,
        "opener": opener,
        "swaps": [hid for hid in comp if hid not in opener[:5]],
        "confidence": confidence,
    }


def hero_bans_for_map(con, match_id: str, map_result_id: int | None = None) -> list[dict]:
    if map_result_id is None:
        rows = con.execute(
            """SELECT * FROM hero_bans WHERE match_id=?
               ORDER BY COALESCE(map_order, 999), COALESCE(ban_order, id), id""",
            (match_id,),
        ).fetchall()
    else:
        rows = con.execute(
            """SELECT * FROM hero_bans WHERE map_result_id=?
               ORDER BY COALESCE(ban_order, id), id""",
            (map_result_id,),
        ).fetchall()
    return [{
        "hero": r["hero_id"],
        "heroId": r["hero_id"],
        "role": rv(r, "role"),
        "teamId": rv(r, "team_id"),
        "mapOrder": rv(r, "map_order"),
        "order": rv(r, "ban_order"),
        "source": rv(r, "source", "unknown"),
        "confidence": rv(r, "confidence"),
        "notes": rv(r, "notes"),
    } for r in rows]


def pick_veto_for_match(con, match_id: str) -> list[dict]:
    rows = con.execute(
        """SELECT * FROM map_veto_events WHERE match_id=? ORDER BY order_index, id""",
        (match_id,),
    ).fetchall()
    return [{
        "order": r["order_index"],
        "teamId": rv(r, "team_id"),
        "map": rv(r, "map_id"),
        "action": rv(r, "action", "unknown"),
        "source": rv(r, "source", "unknown"),
        "notes": rv(r, "notes"),
    } for r in rows]


def rosters_for_match(con, match_id: str, team_a: str, team_b: str) -> dict:
    """FACEIT-sourced lineups: {'a': [players], 'b': [players]}."""
    out = {"a": [], "b": []}
    rows = con.execute(
        """SELECT r.team_id, p.id, p.nickname, p.role, p.faceit_player_id
           FROM match_rosters r JOIN players p ON p.id = r.player_id
           WHERE r.match_id=? ORDER BY p.role, p.nickname""", (match_id,))
    for r in rows:
        side = "a" if r["team_id"] == team_a else "b" if r["team_id"] == team_b else None
        if side:
            out[side].append({"id": r["id"], "nickname": r["nickname"],
                              "role": rv(r, "role"),
                              "faceitPlayerId": rv(r, "faceit_player_id")})
    return out


def comp_timeline(con, map_result_id: int, team_id: str) -> list[dict]:
    """Tracker-generated: every snapshot for this team on this map, in order."""
    rows = con.execute(
        """SELECT * FROM comp_snapshots WHERE map_result_id=? AND team_id=?
           ORDER BY stream_offset_seconds""", (map_result_id, team_id)).fetchall()
    manual = [r for r in rows if rv(r, "source", "cv") == "manual"]
    if manual:
        rows = manual
    out = []
    for s_ in rows:
        heroes = [r["hero_id"] for r in con.execute(
            "SELECT hero_id FROM snapshot_heroes WHERE snapshot_id=? ORDER BY slot",
            (s_["id"],))]
        out.append({"offsetSeconds": s_["stream_offset_seconds"],
                    "heroes": heroes,
                    "confidence": rv(s_, "overall_confidence"),
                    "source": rv(s_, "source", "cv")})
    return out


def winner_side(match_row, winner_team: str | None) -> str | None:
    if winner_team == match_row["team_a"]:
        return "a"
    if winner_team == match_row["team_b"]:
        return "b"
    return None


def load_auto_runs(path: str | None = None) -> list[dict]:
    """Recent run_owcs_auto.py run records for the static site."""
    path = path or os.path.join(db.REPO_ROOT, "data", "auto_runs.json")
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f).get("runs", []) or []
    except (ValueError, OSError):
        return []


def load_ingest_runs(con) -> list[dict]:
    """Full-map ingestion runs (pipeline/ingest_map.py) for the Vision Lab
    — calibration health, team identity, CV ban detections, round/swap
    counts, all linked to that run's evidence report. This is the newer,
    richer sibling of load_auto_runs (which only covers the older capture/
    detect batch path) and is what runs.html leads with."""
    try:
        rows = con.execute(
            "SELECT * FROM ingest_runs ORDER BY created_at DESC").fetchall()
    except Exception:      # table missing on a very old DB -> empty, not fatal
        return []
    out = []
    for r in rows:
        ingest_id = r["id"]
        match = con.execute("SELECT * FROM matches WHERE id=?",
                            (r["match_id"],)).fetchone()
        mr = con.execute(
            "SELECT * FROM map_results WHERE match_id=? AND map_order=?",
            (r["match_id"], r["map_order"])).fetchone()
        map_result_id = mr["id"] if mr else None
        n_rounds = (con.execute(
            "SELECT COUNT(*) FROM map_rounds WHERE map_result_id=?",
            (map_result_id,)).fetchone()[0] if map_result_id else 0)
        n_stints = con.execute(
            "SELECT COUNT(*) FROM hero_stints WHERE ingest_id=?",
            (ingest_id,)).fetchone()[0]
        n_swaps_confirmed = con.execute(
            "SELECT COUNT(*) FROM hero_swaps WHERE ingest_id=? "
            "AND status='confirmed'", (ingest_id,)).fetchone()[0]
        n_swaps_uncertain = con.execute(
            "SELECT COUNT(*) FROM hero_swaps WHERE ingest_id=? "
            "AND status='uncertain'", (ingest_id,)).fetchone()[0]
        n_bans = con.execute(
            "SELECT COUNT(*) FROM hero_bans WHERE ingest_id=?",
            (ingest_id,)).fetchone()[0]
        n_ban_candidates = con.execute(
            "SELECT COUNT(*) FROM ingest_findings WHERE ingest_id=? "
            "AND kind='ban_candidate'", (ingest_id,)).fetchone()[0]
        team_findings = [{
            "side": rv(tf, "field"), "team": rv(tf, "value"),
            "confidence": rv(tf, "confidence"), "status": rv(tf, "status"),
            "notes": rv(tf, "notes"),
        } for tf in con.execute(
            "SELECT * FROM ingest_findings WHERE ingest_id=? "
            "AND kind='team_identity' ORDER BY field", (ingest_id,))]
        try:
            calib_health = (json.loads(r["calibration_health"])
                            if rv(r, "calibration_health") else None)
        except (ValueError, TypeError):
            calib_health = None
        out.append({
            "id": ingest_id,
            "sourceId": rv(r, "source_id"),
            "matchId": r["match_id"],
            "matchTitle": (f"{match['team_a']} vs {match['team_b']}"
                          if match else r["match_id"]),
            "mapOrder": r["map_order"],
            "mapId": rv(mr, "map_id") if mr else None,
            "startOffset": rv(r, "start_offset"),
            "endOffset": rv(r, "end_offset"),
            "detectorVersion": r["detector_version"],
            "calibrationVersion": rv(r, "calibration_version"),
            "status": r["status"],
            "calibrationStatus": rv(r, "calibration_status", "ok"),
            "calibrationHealth": calib_health,
            "reportPath": rv(r, "report_path"),
            "createdAt": rv(r, "created_at"),
            "rounds": n_rounds,
            "stints": n_stints,
            "swapsConfirmed": n_swaps_confirmed,
            "swapsUncertain": n_swaps_uncertain,
            "bansConfirmed": n_bans,
            "banCandidates": n_ban_candidates,
            "teamFindings": team_findings,
        })
    return out


def build_payload(con) -> dict:
    heroes = attach_portraits([dict(r) for r in con.execute(
        "SELECT id, name, role FROM heroes ORDER BY role, name")])
    maps = [dict(r) for r in con.execute(
        "SELECT id, name, mode FROM game_maps ORDER BY name")]
    teams = [{
        "id": r["id"],
        "name": r["name"],
        "region": r["region"],
        "code": r["code"],
        "faceitTeamId": rv(r, "faceit_team_id"),
        "logoUrl": rv(r, "logo_url"),
        "prepNotes": rv(r, "prep_notes"),
    } for r in con.execute(
        "SELECT * FROM teams ORDER BY name")]

    prep_notes = [{
        "id": r["id"],
        "teamId": r["team_id"],
        "opponentTeamId": rv(r, "opponent_team_id"),
        "map": rv(r, "map_id"),
        "noteType": rv(r, "note_type", "general"),
        "note": r["note"],
        "source": rv(r, "source", "manual"),
        "updatedAt": rv(r, "updated_at"),
    } for r in con.execute(
        "SELECT * FROM team_prep_notes ORDER BY team_id, note_type, id")]

    matches_out = []
    for m in con.execute(
        """SELECT * FROM matches
           WHERE status IN ('upcoming','live','final','unknown')
           ORDER BY date, id"""
    ).fetchall():
        maps_out = []
        replay_codes: list[str] = []
        for mr in con.execute(
            "SELECT * FROM map_results WHERE match_id=? ORDER BY map_order",
            (m["id"],),
        ).fetchall():
            info_a = comp_info_for_map(con, mr["id"], m["team_a"])
            info_b = comp_info_for_map(con, mr["id"], m["team_b"])
            bans = hero_bans_for_map(con, m["id"], mr["id"])
            replay_code = rv(mr, "replay_code")
            if replay_code:
                replay_codes.append(replay_code)
            side = winner_side(m, rv(mr, "winner_team"))
            confidence_values = [v for v in [info_a["confidence"], info_b["confidence"], rv(mr, "confidence")] if v is not None]
            confidence = round(sum(confidence_values) / len(confidence_values), 3) if confidence_values else None
            tl_a = comp_timeline(con, mr["id"], m["team_a"])
            tl_b = comp_timeline(con, mr["id"], m["team_b"])
            detected = bool(info_a["comp"] or info_b["comp"])
            maps_out.append({
                "id": mr["id"],
                "map": mr["map_id"],
                "winner": side,                      # derived convenience
                # -------- FACEIT-sourced (matchroom facts) ----------------
                "faceit": {
                    "mapOrder": mr["map_order"],
                    "mapScores": {"a": rv(mr, "score_a"), "b": rv(mr, "score_b")},
                    "winnerTeam": rv(mr, "winner_team"),
                    "pickedByTeam": rv(mr, "picked_by_team"),
                    "vetoAction": rv(mr, "veto_action"),
                    "pickVeto": rv(mr, "pick_veto"),
                    "heroBans": bans,
                    "replayCode": replay_code,
                    "replayCodes": [replay_code] if replay_code else [],
                    "replayExpiresNote": rv(mr, "replay_expires_note"),
                    "vodUrl": rv(mr, "vod_url"),
                    "vodStartSeconds": rv(mr, "vod_start_seconds"),
                    "source": rv(mr, "source", "unknown"),
                    # provenance of the fact fields (replay/bans): 'manual_facts'
                    # if any manual fact bans exist or the map is manual-sourced,
                    # else the map's own source ('faceit' / 'sample').
                    "factSource": ("manual_facts"
                                   if any(b.get("source") == "manual_facts" for b in bans)
                                   else rv(mr, "source", "unknown")),
                },
                # -------- Tracker-generated (replay/VOD/CV/manual) --------
                "tracker": {
                    "detected": detected,
                    "openerCompA": info_a["opener"],
                    "openerCompB": info_b["opener"],
                    "playedHeroesA": info_a["comp"],
                    "playedHeroesB": info_b["comp"],
                    "swapsA": info_a["swaps"],
                    "swapsB": info_b["swaps"],
                    "compTimeline": {"a": tl_a, "b": tl_b},
                    "confidence": confidence if detected else None,
                    "source": ("manual" if any(x["source"] == "manual" for x in (tl_a + tl_b))
                               else (tl_a or tl_b)[0]["source"]) if detected and (tl_a or tl_b) else None,
                    # per-team provenance so each side's badge is accurate
                    "sourceA": tl_a[0]["source"] if tl_a else None,
                    "sourceB": tl_b[0]["source"] if tl_b else None,
                    "confidenceA": info_a["confidence"] if info_a["comp"] else None,
                    "confidenceB": info_b["confidence"] if info_b["comp"] else None,
                    "detectedA": bool(info_a["comp"]),
                    "detectedB": bool(info_b["comp"]),
                },
                "notes": rv(mr, "notes"),
            })

        match_bans = hero_bans_for_map(con, m["id"])
        match_pick_veto = pick_veto_for_match(con, m["id"])
        matches_out.append({
            "id": m["id"],
            "date": m["date"],
            "status": m["status"],
            "region": m["region"],
            "stage": rv(m, "stage") or "",
            "eventName": rv(m, "event_name"),
            "season": rv(m, "season"),
            "division": rv(m, "division"),
            "round": rv(m, "round"),
            "groupName": rv(m, "group_name"),
            "scheduledAt": rv(m, "scheduled_at"),
            "startedAt": rv(m, "started_at"),
            "finishedAt": rv(m, "finished_at"),
            "teamA": m["team_a"],
            "teamB": m["team_b"],
            "teams": [m["team_a"], m["team_b"]],
            "scoreA": rv(m, "score_a", 0),
            "scoreB": rv(m, "score_b", 0),
            "score": {"a": rv(m, "score_a", 0), "b": rv(m, "score_b", 0)},
            "winnerTeam": rv(m, "winner_team"),
            # -------- FACEIT-sourced (matchroom facts) --------------------
            "faceit": {
                "matchId": rv(m, "faceit_match_id"),
                "roomUrl": rv(m, "faceit_room_url"),
                "rosters": rosters_for_match(con, m["id"], m["team_a"], m["team_b"]),
                "pickVeto": match_pick_veto,
                "heroBans": match_bans,
                "replayCodes": replay_codes,
            },
            "sourceUrl": rv(m, "source_url"),
            "vodUrl": rv(m, "vod_url"),
            "rawSource": rv(m, "raw_source"),
            "prepNotes": rv(m, "prep_notes"),
            "updatedAt": rv(m, "updated_at"),
            "maps": maps_out,
        })

    return {
        "generatedAt": dt.datetime.now(dt.timezone.utc).isoformat(),
        "heroes": heroes,
        "maps": maps,
        "teams": teams,
        "teamPrepNotes": prep_notes,
        "matches": matches_out,
        "videoSources": load_video_sources(),
        "autoRuns": load_auto_runs(),
        "ingestRuns": load_ingest_runs(con),
    }


# ===================================================================
# Production public export (public.v1) — window.OWCS_PUBLIC
# ===================================================================
PUBLIC_OUT_PATH = os.path.join(db.REPO_ROOT, "assets", "data",
                               "public_data.v1.js")
PUBLIC_HEADER = """/* =====================================================================
   OWCS Comp Tracker — public_data.v1.js  (PRODUCTION public dataset)
   GENERATED by pipeline/export_data.py --public on {ts} UTC.
   Do not hand-edit. The demo fixture file is never touched by this
   exporter (guarded by pipeline/test_public_site.py).
   ===================================================================== */

window.OWCS_PUBLIC = """

REGIONS = [
    {"id": "all", "name": "All regions", "short": "ALL"},
    {"id": "na", "name": "North America", "short": "NA"},
    {"id": "emea", "name": "EMEA", "short": "EMEA"},
    {"id": "asia", "name": "Asia", "short": "ASIA"},
    {"id": "china", "name": "China", "short": "CN"},
    {"id": "pacific", "name": "Pacific", "short": "PAC"},
]


def _region_id(raw: str | None) -> str:
    r = (raw or "").strip().lower()
    return r if r in {x["id"] for x in REGIONS} else "all"


def _tournament_id(m: Any) -> str:
    """Stable slug from the match's real event/season/stage — never a
    single hardcoded id, so two matches from different events never get
    silently lumped into (or overwrite) the same tournament."""
    import re
    parts = [rv(m, "event_name") or "owcs", rv(m, "season") or "",
             rv(m, "stage") or ""]
    slug = re.sub(r"[^a-z0-9]+", "-", "-".join(parts).lower()).strip("-")
    return slug or "owcs-2026"


def _fmt_clock(seconds: int | None) -> str | None:
    if seconds is None:
        return None
    s = int(seconds)
    return f"{s // 3600}:{(s % 3600) // 60:02d}:{s % 60:02d}"


def _stints_for_map(con, map_result_id: int):
    return con.execute(
        """SELECT * FROM hero_stints WHERE map_result_id=?
           ORDER BY team_id, slot, start_offset""",
        (map_result_id,)).fetchall()


def _snapshot_times(con, map_result_id: int, team_id: str,
                    rounds: list) -> list[int]:
    """Round starts + every moment this team's comp changed."""
    times = {int(r["start_offset"]) for r in rounds
             if rv(r, "start_offset") is not None}
    for s in con.execute(
            """SELECT status, offset_seconds FROM hero_swaps
               WHERE map_result_id=? AND team_id=? AND status='confirmed'""",
            (map_result_id, team_id)):
        times.add(int(s["offset_seconds"]))
    return sorted(times)


def _comp_at(stints, team_id: str, t: int) -> tuple[list, list]:
    """(heroes[5], contributing stint rows) for one team at time t."""
    heroes, rows = [], []
    for slot in range(1, 6):
        cand = [s for s in stints
                if s["team_id"] == team_id and s["slot"] == slot
                and s["start_offset"] <= t + 15
                and (rv(s, "end_offset") or 10**9) >= t]
        if cand:
            # the stint that started most recently before t wins
            best = sorted(cand, key=lambda s: -s["start_offset"])[0]
            heroes.append(best["hero_id"])
            rows.append(best)
    return heroes, rows


def _nearest_frame(frames_dir_rel: str, t: int) -> str | None:
    """Closest copied evidence frame (reports/.../frames/frame_<t>.jpg)."""
    d = os.path.join(db.REPO_ROOT, frames_dir_rel)
    if not os.path.isdir(d):
        return None
    best, best_d = None, None
    for fn in os.listdir(d):
        if not fn.startswith("frame_"):
            continue
        try:
            ft = int(fn.split("_")[1].split(".")[0])
        except ValueError:
            continue
        dist = abs(ft - t)
        if best_d is None or dist < best_d:
            best_d, best = dist, fn
    if best is not None and best_d is not None and best_d <= 60:
        return f"{frames_dir_rel}/{best}"
    return None


def _layout_for_source(source_id: str | None) -> str | None:
    """Resolve a source id to its calibration layout file. Registered
    sources declare it in video_sources.json; ingest-only sources (e.g.
    owcs-jksix-qwc) follow the slug convention layouts/<id_>.json."""
    if not source_id:
        return None
    for s in load_video_sources():
        if s["id"] == source_id and s.get("layout"):
            p = os.path.join(db.REPO_ROOT, s["layout"])
            return p if os.path.exists(p) else None
    slug = source_id.replace("-", "_")
    p = os.path.join(db.REPO_ROOT, "layouts", f"{slug}.json")
    return p if os.path.exists(p) else None


def calibration_summary(source_id: str | None, roster: int) -> dict | None:
    """Compact, honest autocalibration provenance for a broadcast: the
    confidence the auto-calibrator earned, whether the gameplay-filter
    probe is present, and how much of the roster is templated. Powers the
    'why you can trust this footage' story on team/match pages. Returns
    None when the layout can't be found (never invents numbers)."""
    import re as _re
    path = _layout_for_source(source_id)
    if not path:
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            layout = json.load(f)
    except (OSError, ValueError):
        return None
    cal = layout.get("calibration") or {}
    tdir = layout.get("templates_dir")
    heroes = 0
    if tdir and os.path.isdir(os.path.join(db.REPO_ROOT, tdir)):
        name_re = _re.compile(r"^([a-z0-9_-]+?)(?:\.(?:v\d+|[a-z]))?\.png$")
        seen = set()
        for fn in os.listdir(os.path.join(db.REPO_ROOT, tdir)):
            m = name_re.match(fn)
            if m:
                seen.add(m.group(1))
        heroes = len(seen)
    return {
        "sourceId": source_id,
        "confidence": cal.get("confidence"),
        "hudProbe": bool(layout.get("hud_probe")),
        "rejectMarkers": len(layout.get("reject") or []),
        "templateHeroes": heroes,
        "roster": roster,
        "frameSize": [layout.get("frame_width"), layout.get("frame_height")],
    }


def build_public_payload(con) -> dict:
    """The production public.v1 dataset, built ONLY from reviewed/staged
    DB state: matches, map_results, hero_stints (approved statuses),
    hero_swaps, ingest_runs. Nothing is invented; missing facts stay null
    with honest notes."""
    now = dt.datetime.now(dt.timezone.utc).isoformat()
    heroes = attach_portraits(
        [{"id": r["id"], "name": r["name"], "role": r["role"]}
         for r in con.execute("SELECT * FROM heroes ORDER BY role, name")])
    maps_catalog = [{"id": r["id"], "name": r["name"], "mode": r["mode"]}
                    for r in con.execute(
                        "SELECT * FROM game_maps ORDER BY name")]

    roster_size = con.execute("SELECT COUNT(*) FROM heroes").fetchone()[0]
    ingest_rows = con.execute(
        "SELECT * FROM ingest_runs WHERE status='complete'").fetchall()
    match_ids = sorted({r["match_id"] for r in ingest_rows
                        if r["match_id"]})
    hero_bans_out: list[dict] = []

    teams_needed: set[str] = set()
    matches_out, runs_out, snaps_out, players_out = [], [], [], []
    swaps_out: list[dict] = []
    vod_out: dict[str, dict] = {}
    tournaments_by_id: dict[str, dict] = {}

    for mid in match_ids:
        m = con.execute("SELECT * FROM matches WHERE id=?",
                        (mid,)).fetchone()
        if m is None:
            continue
        teams_needed.update((m["team_a"], m["team_b"]))
        tid = _tournament_id(m)
        maps_out = []
        for mr in con.execute(
                """SELECT * FROM map_results WHERE match_id=?
                   ORDER BY map_order""", (mid,)).fetchall():
            rounds = con.execute(
                """SELECT * FROM map_rounds WHERE map_result_id=?
                   ORDER BY round_index""", (mr["id"],)).fetchall()
            stints = _stints_for_map(con, mr["id"])
            run = next((r for r in ingest_rows
                        if r["match_id"] == mid
                        and r["map_order"] == mr["map_order"]), None)
            map_pub_id = f"{mid}-m{mr['map_order']}"
            mode = next((c["mode"] for c in maps_catalog
                         if c["id"] == mr["map_id"]), None)
            maps_out.append({
                "id": map_pub_id,
                "order": mr["map_order"],
                "map": mr["map_id"],
                "mode": mode,
                "winner": rv(mr, "winner_team"),
                "scoreA": rv(mr, "score_a"),
                "scoreB": rv(mr, "score_b"),
                # per-round capture % is not measured by the CV pipeline
                # yet -> null means the page renders its honest fallback.
                # roundCount IS real (segmented by the round-emblem detector)
                # — the honest first step toward per-submap detail.
                "scoreDetail": None,
                "roundCount": len(rounds),
                # real round windows from the round-emblem detector —
                # broadcast offsets in seconds, ±1 sample (~5 s).
                "rounds": [{"index": r_["round_index"],
                            "start": rv(r_, "start_offset"),
                            "end": rv(r_, "end_offset"),
                            "confidence": rv(r_, "confidence"),
                            "source": rv(r_, "source", "cv")}
                           for r_ in rounds],
                "pickedBy": rv(mr, "picked_by_team"),
                "pickNote": None,
            })
            # hero swaps for this map — the temporal-consensus verdicts,
            # confirmed AND rejected. Confirmed rows carry before/after
            # evidence crops; rejected rows carry the honest reason they
            # were thrown out. Nothing here is invented.
            for s in con.execute(
                    """SELECT * FROM hero_swaps WHERE map_result_id=?
                       ORDER BY offset_seconds""", (mr["id"],)):
                evb, eva = rv(s, "evidence_before"), rv(s, "evidence_after")
                swaps_out.append({
                    "id": f"sw-{map_pub_id}-{s['team_id']}-{s['slot']}-"
                          f"{s['offset_seconds']}-{s['status']}",
                    "matchId": mid,
                    "mapId": map_pub_id,
                    "teamId": s["team_id"],
                    "side": rv(s, "side"),
                    "slot": rv(s, "slot"),
                    "fromHero": s["from_hero"],
                    "toHero": s["to_hero"],
                    "offset": rv(s, "offset_seconds"),
                    "confidence": rv(s, "confidence"),
                    "status": s["status"],
                    "reason": rv(s, "reason"),
                    "evidenceBefore": evb if evb and os.path.exists(
                        os.path.join(db.REPO_ROOT, evb)) else None,
                    "evidenceAfter": eva if eva and os.path.exists(
                        os.path.join(db.REPO_ROOT, eva)) else None,
                    "ingestId": rv(s, "ingest_id"),
                })
            # hero bans for this map (real match facts; empty when the
            # broadcast/import recorded none — the UI says so honestly).
            for b in con.execute(
                    """SELECT * FROM hero_bans WHERE match_id=?
                       AND (map_result_id=? OR map_result_id IS NULL)
                       ORDER BY COALESCE(ban_order, id)""",
                    (mid, mr["id"])):
                hero_bans_out.append({
                    "id": f"ban-{map_pub_id}-{b['hero_id']}-{rv(b, 'team_id') or 'x'}",
                    "matchId": mid,
                    "mapId": map_pub_id,
                    "hero": b["hero_id"],
                    "teamId": rv(b, "team_id"),
                    "source": rv(b, "source", "manual"),
                })
            if run is None:
                continue
            frames_rel = f"reports/ingest/{run['id']}/frames"
            approved = {"auto-high", "reviewed"}
            for team in (m["team_a"], m["team_b"]):
                for t in _snapshot_times(con, mr["id"], team, rounds):
                    heroes5, rows = _comp_at(stints, team, t)
                    if len(heroes5) != 5:
                        continue
                    statuses = {r_["status"] for r_ in rows}
                    review = ("auto-high" if statuses <= approved
                              else "needs-review")
                    manual = any(rv(r_, "manual_override") for r_ in rows)
                    confs = [rv(r_, "mean_conf") for r_ in rows
                             if rv(r_, "mean_conf") is not None]
                    side = rows[0]["side"] if rows else None
                    snaps_out.append({
                        "id": f"cs-{map_pub_id}-{team}-{t}",
                        "matchId": mid,
                        "mapId": map_pub_id,
                        "teamId": team,
                        "side": side,
                        "timestamp": t,
                        "heroes": heroes5,
                        "source": "manual" if manual else "cv",
                        "confidence": (round(sum(confs) / len(confs), 3)
                                       if confs else None),
                        "reviewStatus": review,
                        "evidenceRunId": run["id"],
                        "evidenceFrame": _nearest_frame(frames_rel, t),
                    })

        run_ids = [r["id"] for r in ingest_rows if r["match_id"] == mid]
        for r in ingest_rows:
            if r["match_id"] != mid:
                continue
            frames_rel = f"reports/ingest/{r['id']}/frames"
            frames = []
            fdir = os.path.join(db.REPO_ROOT, frames_rel)
            if os.path.isdir(fdir):
                for fn in sorted(os.listdir(fdir)):
                    if fn.startswith("frame_"):
                        try:
                            off = int(fn.split("_")[1].split(".")[0])
                        except ValueError:
                            continue
                        frames.append({"offset": off,
                                       "file": f"{frames_rel}/{fn}",
                                       "layoutDebug": None})
            crops = []
            for s in con.execute(
                    """SELECT evidence_before, evidence_after
                       FROM hero_swaps WHERE ingest_id=?
                       AND status='confirmed'""", (r["id"],)):
                for c in (s["evidence_before"], s["evidence_after"]):
                    if c and os.path.exists(os.path.join(db.REPO_ROOT, c)):
                        crops.append(c)
            runs_out.append({
                "id": r["id"],
                "matchId": mid,
                "sourceId": rv(r, "source_id"),
                "window": {"start": _fmt_clock(rv(r, "start_offset")),
                           "end": _fmt_clock(rv(r, "end_offset")),
                           "every": 5},
                "requestedHeight": 720,
                "actualWidth": 1280,
                "actualHeight": 720,
                "clipMode": "direct-url-cut",
                "status": "needs-review",
                "reportPath": rv(r, "report_path"),
                "createdAt": rv(r, "created_at"),
                "frames": frames,
                "crops": crops,
                "note": ("full-map CV ingestion "
                         f"({rv(r, 'detector_version')}, calibration "
                         f"{rv(r, 'calibration_version')})"),
                # autocalibration provenance for the 'trust this footage'
                # story — real numbers from the source's layout, or null.
                "calibration": calibration_summary(
                    rv(r, "source_id"), roster_size),
                "calibrationStatus": rv(r, "calibration_status", "ok"),
                "calibrationVersion": rv(r, "calibration_version"),
            })

        for p in con.execute(
                """SELECT r.team_id, p.* FROM match_rosters r
                   JOIN players p ON p.id=r.player_id
                   WHERE r.match_id=?""", (mid,)):
            players_out.append({"id": p["id"], "teamId": p["team_id"],
                                "handle": p["nickname"],
                                "role": rv(p, "role")})

        vurl = rv(m, "vod_url")
        if vurl:
            vod_out[vurl] = {
                "id": rv(m, "source_ref") or f"vod-{mid}",
                "provider": "youtube",
                "url": vurl,
                "title": rv(m, "event_name") or "OWCS broadcast VOD",
                "matchIds": [mid],
                "heightAvailable": 1080,
            }

        stage_name = rv(m, "stage") or "Matches"
        matches_out.append({
            "id": mid,
            "tournamentId": tid,
            "stageId": f"{tid}-stage",
            "roundId": None,
            "teamA": m["team_a"],
            "teamB": m["team_b"],
            "bestOf": 5,
            "scheduledAt": f"{m['date']}T00:00:00+00:00",
            "status": "completed",
            "scoreA": rv(m, "score_a") or None,
            "scoreB": rv(m, "score_b") or None,
            "winner": rv(m, "winner_team"),
            "streamUrl": vurl,
            "faceitUrl": rv(m, "faceit_room_url"),
            "liquipediaUrl": None,
            "casters": [],
            "sources": [{"type": "vod", "url": vurl,
                         "lastSynced": now}] if vurl else [],
            "captureStatus": "needs-review",
            "captureRunId": run_ids[0] if run_ids else None,
            "summary": (f"{len(maps_out)} map(s) captured and ingested by "
                        "the CV pipeline; series score not yet recorded — "
                        "only verified data is shown."),
            "maps": maps_out,
        })

        if tid not in tournaments_by_id:
            tournaments_by_id[tid] = {
                "id": tid,
                "name": rv(m, "event_name") or "OWCS 2026",
                "series": "OWCS",
                "region": _region_id(rv(m, "region")),
                "tier": "S",
                "year": 2026,
                "startsAt": f"{m['date']}T00:00:00+00:00",
                "endsAt": None,
                "status": "completed",
                "prizePool": None,
                "teamIds": set(),
                "winnerTeamId": None,
                "summary": (f"{stage_name}. Matches appear here as their "
                            "VODs are captured and reviewed."),
                "logoUrl": None,
                "sources": [],
                "stages": [{"id": f"{tid}-stage", "name": stage_name,
                            "order": 1, "format": "Double elimination",
                            "status": "completed"}],
                "standings": [],
            }
        tourn = tournaments_by_id[tid]
        tourn["teamIds"].update((m["team_a"], m["team_b"]))
        if vurl and not any(s["url"] == vurl for s in tourn["sources"]):
            tourn["sources"].append({"type": "vod", "url": vurl,
                                     "lastSynced": now})

    tournaments_out = [dict(t, teamIds=sorted(t["teamIds"]))
                       for t in tournaments_by_id.values()]

    teams = [{"id": r["id"], "name": r["name"], "code": r["code"],
              "region": _region_id(rv(r, "region")),
              "logoUrl": rv(r, "logo_url")}
             for r in con.execute("SELECT * FROM teams ORDER BY name")
             if r["id"] in teams_needed]

    return {
        "meta": {
            "schema": "public.v1",
            "demo": False,
            "generatedAt": now,
            "note": ("Production export from data/owcs.sqlite — only "
                     "captured, staged and reviewed data; no invented "
                     "values."),
        },
        "regions": REGIONS,
        "teams": teams,
        "players": players_out,
        "tournaments": tournaments_out,
        "bracketRounds": [],
        "extraRounds": [],
        "bracketMatches": [],
        "matches": matches_out,
        "heroBans": hero_bans_out,
        "heroSwaps": swaps_out,
        "captureRuns": runs_out,
        "compSnapshots": snaps_out,
        "vodSources": list(vod_out.values()),
        "heroes": heroes,
        "mapsCatalog": maps_catalog,
        "patches": [],
    }


def write_public(con) -> str:
    payload = build_public_payload(con)
    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M")
    body = (PUBLIC_HEADER.format(ts=ts)
            + json.dumps(payload, indent=1, ensure_ascii=False) + ";\n")
    os.makedirs(os.path.dirname(PUBLIC_OUT_PATH), exist_ok=True)
    with open(PUBLIC_OUT_PATH, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"Wrote {PUBLIC_OUT_PATH}: {len(payload['matches'])} matches, "
          f"{len(payload['compSnapshots'])} comp snapshots, "
          f"{len(payload['captureRuns'])} capture runs.")
    return PUBLIC_OUT_PATH


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stdout", action="store_true",
                    help="print JSON instead of writing data.js")
    ap.add_argument("--public", action="store_true",
                    help="ALSO write assets/data/public_data.v1.js "
                         "(production public dataset)")
    args = ap.parse_args()

    con = db.connect()
    payload = build_payload(con)

    if args.stdout:
        json.dump(payload, sys.stdout, indent=1)
        return

    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M")
    body = HEADER.format(ts=ts) + json.dumps(payload, indent=1, ensure_ascii=False) + ";\n"
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(body)
    bans = sum(len(g["faceit"]["heroBans"]) for m_ in payload["matches"] for g in m_["maps"])
    detected = sum(1 for m_ in payload["matches"] for g in m_["maps"] if g["tracker"]["detected"])
    total = sum(len(m_["maps"]) for m_ in payload["matches"])
    print(f"Wrote {OUT_PATH}: {len(payload['matches'])} matches, "
          f"{total} maps ({detected} with tracker comps, "
          f"{total - detected} FACEIT-only), {bans} hero bans.")
    if args.public:
        write_public(con)


if __name__ == "__main__":
    main()
