#!/usr/bin/env python3
"""
test_end_to_end_offline.py — the whole loop, offline, on a synthetic broadcast.

Every other suite tests one stage. This one drives the REAL modules through
the whole chain, in order, on a video this test generates with ffmpeg:

   1. ingest-link            paste one URL -> one deterministic job
   2. source authorization   auto-approved from the verified registry
   3. duration + disk preflight, then the real download bookkeeping
   4. 360p scan proxy        generated by real ffmpeg from the real source
   5. resolve-layout         real structural fingerprint -> reuse a layout
   6. segmentation           real gameplay classification ON THE PROXY,
                             two map windows found, desk content rejected
   7. propose-identity       map/mode/teams/sides/order/players with evidence
   8. accept-proposed        approved through the same human gate
   9. extract_segment_clip   cut from the FULL-RESOLUTION source, not the proxy
  10. intake-export          the operator panel's data
  11. idempotency            re-pasting the link changes nothing

What it deliberately does NOT claim: no YouTube network call happens here.
The download step injects a fetcher that copies the generated file, which is
exactly the boundary a sandbox without YouTube egress can reach. Everything
downstream of "a real 720p file is on disk" is the real code path.

Skips (with a reason) when ffmpeg/ffprobe are unavailable.

Run: python3 pipeline/test_end_to_end_offline.py
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
REPO = os.path.dirname(HERE)

import cv2  # noqa: E402
import numpy as np  # noqa: E402

import db as content_db  # noqa: E402
import map_identify as mid  # noqa: E402
import ocr_hud  # noqa: E402
import player_identify as pid  # noqa: E402
import video_ingest as vi  # noqa: E402
from automation import job_store as js  # noqa: E402
from automation import layout_resolver as lr  # noqa: E402
from automation import link_intake as li  # noqa: E402
from automation import locks as lk  # noqa: E402
from automation import segment_identity as si  # noqa: E402
from automation import segmentation as seg  # noqa: E402
from automation import state_machine as sm  # noqa: E402
from automation import worker as wk  # noqa: E402
from automation import youtube_api as yt  # noqa: E402

from test_automation_layout_resolver import (  # noqa: E402
    FRAME_H, FRAME_W, desk_frame, gameplay_frame, hud_layout)
from test_automation_segment_identity import (  # noqa: E402
    KNOWN_MAPS, KNOWN_TEAMS, ROSTER, box_in, item)

HAVE_FFMPEG = bool(shutil.which("ffmpeg") and shutil.which("ffprobe"))

VIDEO_ID = "dQw4w9WgXcQ"
CHANNEL_ID = "UCiAInBL9kUzz1XRxk66v-gw"
REGISTRY = [{"id": "ow_esports_global", "platform": "youtube",
             "channelId": CHANNEL_ID, "region": "global", "language": "en",
             "official": True, "enabled": True, "verifiedStatus": "verified"}]

# The synthetic broadcast's shape, in seconds of a 1 fps video: desk, map 1,
# a break, map 2, outro. Short enough to build fast, long enough for the
# 10-second segmentation sampler to see structure.
TIMELINE = ([("desk", 40)] + [("map1", 120)] + [("desk", 40)]
            + [("map2", 120)] + [("desk", 30)])
FPS = 1


def _fake_youtube_client() -> yt.YouTubeClient:
    body = {"items": [{
        "id": VIDEO_ID,
        "snippet": {"channelId": CHANNEL_ID,
                    "channelTitle": "Overwatch Esports",
                    "title": "OWCS 2026 Stage 2 | Al Qadsiah vs Twisted Minds "
                             "| Day 1 Map 1",
                    "description": "Full broadcast VOD. Bo3.",
                    "publishedAt": "2026-07-20T10:00:00Z",
                    "liveBroadcastContent": "none"},
        "status": {"privacyStatus": "public"},
        "contentDetails": {"duration": "PT5M50S"},
        "liveStreamingDetails": {"actualStartTime": "2026-07-20T10:00:00Z",
                                 "actualEndTime": "2026-07-20T10:05:50Z"},
    }]}
    return yt.YouTubeClient(transport=lambda u, h: (200, json.dumps(body), None),
                           cache_dir=None)


@unittest.skipUnless(HAVE_FFMPEG, "needs ffmpeg + ffprobe")
class TestWholeLoopOffline(unittest.TestCase):
    """One ordered walk through the loop. Deliberately a single test: each
    stage consumes the previous stage's real output, so splitting them would
    either re-do the expensive video build or fake the hand-off."""

    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory(prefix="owcs_e2e_")
        cls.layout = hud_layout(templates_dir="templates/owcs_e2e")
        cls.source = cls._build_broadcast(
            os.path.join(cls.tmp.name, "broadcast.mp4"))

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    @classmethod
    def _build_broadcast(cls, out_path: str) -> str:
        """A real 1280x720 H.264 file whose gameplay stretches satisfy the
        SAME structural HUD probe production detection uses, and whose desk
        stretches do not."""
        frames_dir = os.path.join(cls.tmp.name, "src_frames")
        os.makedirs(frames_dir, exist_ok=True)
        n = 0
        for kind, seconds in TIMELINE:
            for _ in range(seconds * FPS):
                if kind == "desk":
                    frame = desk_frame(FRAME_W, FRAME_H)
                else:
                    # Distinct team hues per map so side continuity has real
                    # signal, and fresh portrait noise per frame so texture
                    # is measured rather than duplicated.
                    frame = gameplay_frame(cls.layout)
                cv2.imwrite(os.path.join(frames_dir, f"{n:06d}.png"), frame)
                n += 1
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
             "-framerate", str(FPS), "-i",
             os.path.join(frames_dir, "%06d.png"),
             "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
             out_path],
            check=True, capture_output=True)
        shutil.rmtree(frames_dir, ignore_errors=True)
        return out_path

    def _ocr_reader(self):
        """A fake OCR reader that prints the map name and both team names in
        the right zones — the only injected piece in the identity stage."""
        map_zones = mid.zones_for(self.layout, FRAME_W, FRAME_H)
        team_zones = {k: ocr_hud.zone_px(v, FRAME_W, FRAME_H)
                      for k, v in ocr_hud.DEFAULT_ZONES.items()}
        plate_zones = {(z["side"], z["index"]): z["zone"]
                       for z in pid.slot_nameplate_zones(self.layout,
                                                         FRAME_W, FRAME_H)}
        handles = {("a", i): h for i, h in
                   enumerate(["LIP", "Smurf", "Fielder", "Hanbin", "Shu"], 1)}
        handles.update({("b", i): h for i, h in
                        enumerate(["ZOX", "Hydron", "Kilo", "Hawk", "Chiyo"], 1)})

        def read(frame_bgr):
            h, w = frame_bgr.shape[:2]
            sx, sy = w / FRAME_W, h / FRAME_H

            def sc(zone):
                x, y, zw, zh = zone
                return [int(x * sx), int(y * sy), max(2, int(zw * sx)),
                        max(2, int(zh * sy))]
            items = [item("NEPAL", box_in(sc(map_zones["objective_strip"]))),
                     item("Al Qadsiah", box_in(sc(team_zones["team_left"]))),
                     item("Twisted Minds", box_in(sc(team_zones["team_right"])))]
            for key, handle in handles.items():
                items.append(item(handle, box_in(sc(plate_zones[key]))))
            return items
        return read

    def test_the_whole_loop(self):
        tmp = self.tmp.name
        evidence: dict[str, object] = {}

        # ---- content DB: the facts a match must already exist against -----
        content = content_db.connect(os.path.join(tmp, "owcs.sqlite"))
        content_db.init_schema(content)
        for m in KNOWN_MAPS:
            content.execute("INSERT OR REPLACE INTO game_maps (id,name,mode) "
                            "VALUES (?,?,?)", (m["id"], m["name"], m["mode"]))
        for t in KNOWN_TEAMS:
            content.execute("INSERT OR REPLACE INTO teams (id,name,code,region) "
                            "VALUES (?,?,?,?)",
                            (t["id"], t["name"], t["code"], "emea"))
        for p in ROSTER:
            content.execute("INSERT OR REPLACE INTO players "
                            "(id,team_id,nickname) VALUES (?,?,?)",
                            (p["id"], p["teamId"], p["handle"]))
        content.execute(
            """INSERT INTO matches (id,date,team_a,team_b,event_name)
               VALUES ('m-e2e','2026-07-20','qadsiah','twis','OWCS E2E')""")
        content.commit()
        self.addCleanup(content.close)

        store = js.JobStore(os.path.join(tmp, "automation.sqlite"))
        self.addCleanup(store.close)
        locks = lk.LockManager(store.con, lease_seconds=300)

        # =============== STAGE 1-2: paste one URL, get one job =============
        res = li.ingest_link(store,
                             f"https://www.youtube.com/live/{VIDEO_ID}?t=90",
                             client=_fake_youtube_client(), channels=REGISTRY,
                             requested_by="e2e")
        self.assertTrue(res["created"])
        self.assertEqual(res["videoId"], VIDEO_ID)
        self.assertEqual(res["source"]["state"], li.SOURCE_APPROVED)
        self.assertTrue(res["source"]["autoApproved"])
        self.assertEqual(res["state"], sm.ARCHIVED)
        job_key = res["jobKey"]
        evidence["1_intake"] = {"jobKey": job_key, "state": res["state"],
                                "source": res["source"]["reasonCode"]}

        # The operator supplied ONLY a URL: identity is honestly unknown.
        job = store.get(job_key)
        for field in ("matchId", "teamA", "teamB", "expectedLayoutId"):
            self.assertIsNone(job.payload[field], field)
        # A match id is the one thing a human must attach (a video never
        # invents a match); do it explicitly, as an operator would.
        store.update_payload(job_key, {"matchId": "m-e2e"})

        # ====== STAGE 3-4: duration, disk preflight, download, proxy =======
        media_root = os.path.join(tmp, "media")
        copies = {"n": 0}

        def fake_fetch(url, out, height=720, **kw):
            """Stands in for the yt-dlp call the sandbox cannot make. Produces
            the REAL generated file at `out`, so every downstream stage runs
            on real media."""
            copies["n"] += 1
            os.makedirs(os.path.dirname(out), exist_ok=True)
            shutil.copyfile(self.source, out)
            return {"path": out, "sizeBytes": os.path.getsize(out),
                    "resumed": False, "reused": False,
                    "format": f"bestvideo[height<={height}]",
                    "partialBytesBefore": 0}

        dl = wk.download_job(
            store, locks, store.get(job_key), worker_id="e2e-worker",
            media_root=media_root, min_free_gb=0.001,
            official_channel_ids={CHANNEL_ID},
            probe_fn=lambda u: {"title": "OWCS E2E", "duration": 350},
            download_full_fn=fake_fetch)          # proxy_fn stays REAL ffmpeg
        self.assertTrue(dl["ok"], dl)
        job = store.get(job_key)
        self.assertEqual(job.state, sm.DOWNLOADED)
        media = job.payload["media"]
        self.assertEqual(len(media["sha256"]), 64)
        self.assertEqual(media["requestedHeight"], 720)
        self.assertTrue(job.payload["diskPreflight"]["ok"])
        self.assertIsNotNone(job.payload["diskPreflight"]["neededGb"])
        # The proxy is REAL: built by ffmpeg from the real source.
        proxy = media["proxy"]
        self.assertEqual(proxy["height"], 360)
        self.assertEqual(len(proxy["sha256"]), 64)
        scan_path = wk.scan_path_for(job, repo_root=REPO)
        source_path = wk.source_path_for(job, repo_root=REPO)
        self.assertTrue(os.path.exists(scan_path))
        self.assertTrue(os.path.exists(source_path))
        # And it is genuinely smaller + genuinely 360p.
        self.assertLess(os.path.getsize(scan_path), os.path.getsize(source_path))
        self.assertEqual((vi.probe_clip_resolution(scan_path) or {})["height"],
                         360)
        evidence["3_download"] = {"sha256": media["sha256"][:16],
                                  "durationSeconds": media["durationSeconds"],
                                  "diskPreflight": job.payload["diskPreflight"]["reason"]}
        evidence["4_proxy"] = {"height": proxy["height"],
                               "sizeBytes": proxy["sizeBytes"],
                               "sourceBytes": media["fileSizeBytes"]}

        # ============ STAGE 5: resolve the layout from evidence ============
        layouts_dir = os.path.join(tmp, "layouts")
        os.makedirs(layouts_dir)
        with open(os.path.join(layouts_dir, "owcs_e2e.json"), "w",
                  encoding="utf-8") as f:
            json.dump(self.layout, f)
        # A decoy: a real layout for a DIFFERENT broadcast package.
        with open(os.path.join(layouts_dir, "owcs_other_package.json"), "w",
                  encoding="utf-8") as f:
            json.dump(hud_layout(chip_y=520, left_x=200, right_x=1000,
                                 pitch=55), f)
        lay_res = lr.resolve_layout(
            store, store.get(job_key), scan_path=scan_path,
            layouts_dir=layouts_dir,
            reports_dir=os.path.join(tmp, "reports", "layout"),
            sample_count=12)
        self.assertTrue(lay_res["ok"], lay_res)
        self.assertEqual(lay_res["layoutId"], "owcs_e2e",
                         "the matching package must win over the decoy")
        record = lay_res["record"]
        self.assertEqual(record["decision"], "reuse")
        self.assertFalse(record["approvalRequired"])
        scores = {c["layoutId"]: c["score"] for c in record["candidates"]}
        self.assertGreater(scores["owcs_e2e"], scores["owcs_other_package"])
        self.assertEqual(scores["owcs_other_package"], 0.0)
        # Marker harvesting saw real gameplay AND real break frames.
        harvested = record["markers"]["harvested"]
        self.assertIn("gameplay", harvested)
        self.assertIn("break", harvested)
        self.assertIn("round_emblem", record["markers"]["missingStates"])
        evidence["5_layout"] = {"chosen": lay_res["layoutId"],
                                "scores": scores,
                                "reason": record["reason"],
                                "markers": sorted(harvested)}

        # ====== STAGE 6: segmentation on the PROXY, desk content rejected ==
        import capture
        layout = capture.load_layout(os.path.join(layouts_dir, "owcs_e2e.json"))
        candidates = seg.generate_candidates(
            scan_path, layout, out_dir=os.path.join(tmp, "thumbs"), interval=10)
        self.assertEqual(len(candidates), 2,
                         f"expected the two map windows, got "
                         f"{[(c['start_time'], c['end_time']) for c in candidates]}")
        for c in candidates:
            self.assertEqual(c["signals"]["method"], "hud-structural-probe")
            self.assertEqual(len(c["thumbnails"]), 3)
            for t in c["thumbnails"]:
                self.assertTrue(os.path.exists(
                    os.path.join(REPO, t["path"])) or os.path.exists(t["path"]))
        # The desk stretches are NOT inside a candidate window.
        first, second = candidates
        self.assertGreater(second["start_time"], first["end_time"],
                           "the break between maps must separate them")
        ids = seg.store_candidates(store.con, VIDEO_ID, "m-e2e", candidates,
                                   source_job_key=job_key)
        self.assertEqual(len(ids), 2)
        evidence["6_segments"] = [
            {"id": i, "start": c["start_time"], "end": c["end_time"],
             "gameplayFrames": c["signals"]["gameplaySamples"],
             "rejections": c["signals"]["rejections"]}
            for i, c in zip(ids, candidates)]

        # ============ STAGE 7: identity proposals with evidence ============
        read_fn = self._ocr_reader()
        proposals = {}
        for sid in ids:
            segment = seg.get_segment(store.con, sid)
            frames = lr.extract_sample_frames(
                scan_path, os.path.join(tmp, "idframes", str(sid)), count=6,
                duration_seconds=segment["end_time"] - segment["start_time"])
            # Sample inside THIS segment's window.
            frames = [(segment["start_time"] + off, path)
                      for off, path in frames]
            inside = os.path.join(tmp, "idframes_in", str(sid))
            os.makedirs(inside, exist_ok=True)
            picked = []
            span = segment["end_time"] - segment["start_time"]
            for k in range(4):
                t = segment["start_time"] + span * (k + 1) / 5.0
                out = os.path.join(inside, f"f{int(t):06d}.png")
                subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error",
                                "-y", "-ss", str(t), "-i", scan_path,
                                "-frames:v", "1", out],
                               check=False, capture_output=True)
                if os.path.exists(out):
                    picked.append((t, out))
            self.assertTrue(picked, "must be able to sample inside a segment")
            proposal = si.propose_identity(
                store.con, content, segment, layout=layout, frames=picked,
                read_fn=read_fn, match_id="m-e2e")
            si.store_proposals(store.con, sid, proposal)
            proposals[sid] = proposal
            # Every signal is present, with provenance.
            for signal in si.SIGNALS:
                self.assertIn(signal, proposal, signal)
                self.assertIn("source", proposal[signal])
                self.assertIn("confidence", proposal[signal])
            self.assertEqual(proposal["map"]["value"], "nepal")
            self.assertEqual(proposal["mode"]["value"], "Control")
            self.assertEqual(proposal["mode"]["source"], "map-catalog")
            self.assertEqual(proposal["teamA"]["value"], "qadsiah")
            self.assertEqual(proposal["teamB"]["value"], "twis")
            self.assertEqual(proposal["sideAssignment"]["value"], "team_a_left")
            self.assertEqual(proposal["players"]["value"] and
                             sum(1 for s in proposal["players"]["value"]
                                 if s["player"]), 10)
            self.assertEqual(proposal["identityStatus"], "proposed")
            self.assertEqual(proposal["reviewTasks"], [])
        # Chronological map order, from the segment windows.
        self.assertEqual([proposals[i]["mapOrder"]["value"] for i in ids], [1, 2])
        evidence["7_identity"] = {
            str(i): {"map": proposals[i]["map"]["value"],
                     "mode": proposals[i]["mode"]["value"],
                     "teamA": proposals[i]["teamA"]["value"],
                     "teamB": proposals[i]["teamB"]["value"],
                     "side": proposals[i]["sideAssignment"]["value"],
                     "mapOrder": proposals[i]["mapOrder"]["value"],
                     "playersResolved": sum(
                         1 for s in proposals[i]["players"]["value"]
                         if s["player"])}
            for i in ids}

        # ---- findings: every signal mirrored into the content DB audit ----
        content.execute(
            """INSERT INTO ingest_runs (id, source_id, match_id,
                   detector_version, status)
               VALUES ('e2e-run', ?, 'm-e2e', 'det-e2e', 'running')""",
            (VIDEO_ID,))
        content.commit()
        n_findings = si.record_findings(content, "e2e-run", proposals[ids[0]])
        self.assertEqual(n_findings, len(si.SIGNALS))
        rows = list(content.execute(
            "SELECT field, value, method, confidence, status "
            "FROM ingest_findings WHERE ingest_id='e2e-run'"))
        self.assertEqual(len(rows), len(si.SIGNALS))
        for r in rows:
            self.assertIsNotNone(r["method"], r["field"])

        # ======== STAGE 8: approve through the SAME human gate ============
        for sid in ids:
            row = si.accept_proposed(store.con, sid, layout_id="owcs_e2e")
            self.assertEqual(row["review_status"], "approved")
            self.assertEqual(row["map_name"], "nepal")
            self.assertEqual(row["team_a"], "qadsiah")
        approved = seg.list_segments(store.con, video_id=VIDEO_ID,
                                    review_status="approved")
        self.assertEqual(len(approved), 2)

        # ==== STAGE 9: cut the clip from the FULL-RESOLUTION source ========
        clip_dir = os.path.join(tmp, "clips")
        cut = seg.extract_segment_clip(store.con, ids[0], source_path, clip_dir)
        self.assertTrue(cut["extracted_path"])
        self.assertEqual(len(cut["extracted_hash"]), 64)
        # 720p, not the 360p proxy — this is what detection reads.
        self.assertEqual(cut["extracted_height"], FRAME_H)
        # ...and the proxy is refused outright.
        with self.assertRaises(ValueError) as ctx:
            seg.extract_segment_clip(store.con, ids[1], scan_path, clip_dir)
        self.assertIn("scan proxy", str(ctx.exception))
        evidence["9_clip"] = {"path": cut["extracted_path"],
                              "height": cut["extracted_height"],
                              "sha256": cut["extracted_hash"][:16]}

        # ============ STAGE 10: the operator review panel data ============
        report = li.build_intake_report(store, job_key=job_key)
        self.assertEqual(len(report["jobs"]), 1)
        panel = report["jobs"][0]
        self.assertEqual(panel["state"], sm.DOWNLOADED)
        self.assertEqual(len(panel["segments"]), 2)
        for s in panel["segments"]:
            self.assertEqual(s["reviewStatus"], "approved")
            self.assertEqual(s["confirmed"]["map"], "nepal")
            self.assertTrue(s["proposed"])
            self.assertTrue(s["thumbnails"])
        self.assertEqual(panel["layout"]["layoutId"], "owcs_e2e")
        evidence["10_panel"] = {"nextCommand": panel["nextCommand"],
                                "segments": len(panel["segments"])}

        # ================ STAGE 11: idempotency of the whole thing =========
        again = li.ingest_link(store, f"https://youtu.be/{VIDEO_ID}",
                               client=_fake_youtube_client(), channels=REGISTRY)
        self.assertFalse(again["created"])
        self.assertTrue(again["duplicate"])
        self.assertEqual(again["jobKey"], job_key)
        self.assertEqual(len(store.list_jobs()), 1)
        # Re-running segmentation proposes fresh candidates without touching
        # the approved ones.
        seg.store_candidates(store.con, VIDEO_ID, "m-e2e", candidates,
                             source_job_key=job_key)
        still_approved = seg.list_segments(store.con, video_id=VIDEO_ID,
                                          review_status="approved")
        self.assertEqual(len(still_approved), 2)
        self.assertEqual(copies["n"], 1, "the VOD was fetched exactly once")

        # ---- write the evidence file this run produced --------------------
        out_dir = os.path.join(REPO, "work", "e2e")
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, "evidence.json"), "w",
                  encoding="utf-8") as f:
            json.dump(evidence, f, indent=1, default=str)
            f.write("\n")
        print("\n[e2e] stage evidence -> work/e2e/evidence.json")
        for stage, data in evidence.items():
            print(f"  {stage}: {json.dumps(data, default=str)[:200]}")


if __name__ == "__main__":
    unittest.main(verbosity=2)
