#!/usr/bin/env python3
"""
test_meaningful_diff.py — pipeline/automation/meaningful_diff.py is the
guard that stops discovery.yml/pipeline.yml/update-data.yml from treating
"the generation timestamp moved" as "real data changed". PR #82 is the
live incident: its entire merged diff across data.js, public_data.v1.js
and team_coverage.v1.json was three timestamp fields — no team or
calendar fact actually changed — and a raw `git diff --cached --quiet`
cannot tell that apart from a real change.

Runs against an ISOLATED temporary git repo (never this session's own
working tree).
Run: python3 pipeline/test_meaningful_diff.py
"""
from __future__ import annotations
import os
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "automation"))
import meaningful_diff as md  # noqa: E402
import proc_text  # noqa: E402  (UTF-8 subprocess decoding)


def _git(repo, *args):
    subprocess.run(["git", "-C", repo, *args], check=True,
                    capture_output=True, text=True, **proc_text.PIPE_TEXT)


class _TempRepo(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.repo = self._tmp.name
        _git(self.repo, "init", "-q")
        _git(self.repo, "config", "user.email", "test@example.com")
        _git(self.repo, "config", "user.name", "test")
        self._cwd = os.getcwd()
        os.chdir(self.repo)

    def tearDown(self):
        os.chdir(self._cwd)
        self._tmp.cleanup()

    def _write(self, path, content):
        with open(path, "w", encoding="utf-8", newline="") as f:
            f.write(content)

    def _commit(self, path, content, msg="commit"):
        self._write(path, content)
        _git(self.repo, "add", path)
        _git(self.repo, "commit", "-q", "-m", msg)


class TestNormalize(_TempRepo):
    def test_generatedAt_field_is_blanked(self):
        a = b'{"meta": {"generatedAt": "2026-08-25T23:37:42.524470+00:00"}}'
        b = b'{"meta": {"generatedAt": "2026-08-26T05:06:38.054772+00:00"}}'
        self.assertEqual(md.normalize(a), md.normalize(b))

    def test_banner_timestamp_is_blanked(self):
        a = b"GENERATED by pipeline/export_data.py on 2026-08-25 23:37 UTC\n"
        b = b"GENERATED by pipeline/export_data.py on 2026-08-26 05:06 UTC\n"
        self.assertEqual(md.normalize(a), md.normalize(b))

    def test_a_real_value_change_survives_normalization(self):
        a = b'{"broadcast_located": 4, "generatedAt": "2026-08-25T23:37:42+00:00"}'
        b = b'{"broadcast_located": 0, "generatedAt": "2026-08-26T05:06:38+00:00"}'
        self.assertNotEqual(md.normalize(a), md.normalize(b))

    def test_binary_content_is_compared_exactly(self):
        blob = bytes(range(256))
        self.assertEqual(md.normalize(blob), blob)
        self.assertNotEqual(md.normalize(blob), md.normalize(blob + b"\x00"))


class TestHasMeaningfulChange(_TempRepo):
    def test_timestamp_only_diff_is_not_a_meaningful_change(self):
        self._commit(
            "data.js",
            'window.OWCS_DATA = {"generatedAt": "2026-08-25T23:37:42+00:00"};\n')
        self._write(
            "data.js",
            'window.OWCS_DATA = {"generatedAt": "2026-08-26T05:06:38+00:00"};\n')
        self.assertFalse(md.has_meaningful_change("data.js"))

    def test_a_real_fact_change_is_meaningful(self):
        self._commit(
            "data.js",
            'window.OWCS_DATA = {"generatedAt": "2026-08-25T23:37:42+00:00", '
            '"teams": 40};\n')
        self._write(
            "data.js",
            'window.OWCS_DATA = {"generatedAt": "2026-08-26T05:06:38+00:00", '
            '"teams": 41};\n')
        self.assertTrue(md.has_meaningful_change("data.js"))

    def test_a_brand_new_file_is_meaningful(self):
        self._write("new_export.json", "{}")
        self.assertTrue(md.has_meaningful_change("new_export.json"))

    def test_a_missing_file_is_not_meaningful(self):
        self.assertFalse(md.has_meaningful_change("does_not_exist.json"))

    def test_main_exits_nonzero_only_when_nothing_changed(self):
        self._commit("a.json", '{"generatedAt": "2026-08-25T23:37:42+00:00"}')
        self._write("a.json", '{"generatedAt": "2026-08-26T05:06:38+00:00"}')
        self.assertEqual(md.main(["a.json"]), 1)
        self._write("a.json", '{"generatedAt": "2026-08-26T05:06:38+00:00", "x": 1}')
        self.assertEqual(md.main(["a.json"]), 0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
